import { describe, expect, it } from 'vitest'
import { buildGeometryReview, formatGeometryNumber } from './geometryReview'
import type { ViewerManifest } from '../components/viewer/LazyViewer3D'

const manifest: ViewerManifest = {
  asset_url: '/geometry',
  format: 'flow360-uvf',
  bounding_box: { min: [-1, 0, 2], max: [3, 5, 8] },
  groups: [
    { id: 'face-1', name: 'body00001_face_1', color: '#fff', visible: true, triangles: 8 },
  ],
  vertices: 12,
  elements: 8,
}

describe('buildGeometryReview', () => {
  it('reports dimensions and warns when CAD surfaces have generated names', () => {
    const review = buildGeometryReview({
      id: 'geo-1',
      type: 'Geometry',
      info: { length_unit: { value: 1, units: 'm' } },
      summary: { free_edge_count: 0, non_manifold_edge_count: 0, self_intersection_count: 0 },
    }, manifest, 'processed')

    expect(review.dimensions).toEqual([4, 5, 6])
    expect(review.diagonal).toBeCloseTo(Math.sqrt(77))
    expect(review.unit).toBe('m')
    expect(review.groupsAreAutogenerated).toBe(true)
    expect(review.readiness).toBe('warning')
  })

  it('blocks meshing when units are unresolved or topology has blockers', () => {
    const review = buildGeometryReview({
      id: 'geo-1',
      type: 'Geometry',
      summary: { free_edges: 3 },
    }, manifest, 'processed')

    expect(review.readiness).toBe('blocked')
    expect(review.checks.find((check) => check.key === 'unit')?.level).toBe('blocked')
    expect(review.checks.find((check) => check.key === 'free-edges')?.count).toBe(3)
  })

  it('keeps unavailable diagnostics explicitly unknown', () => {
    const review = buildGeometryReview({
      id: 'geo-1',
      type: 'Geometry',
      info: { length_unit: 'mm' },
    }, manifest, 'processed')

    expect(review.checks.find((check) => check.key === 'non-manifold')?.level).toBe('unknown')
    expect(review.readiness).toBe('warning')
  })

  it('does not flag a single connected component as disconnected geometry', () => {
    const review = buildGeometryReview({
      id: 'geo-1',
      type: 'Geometry',
      info: { length_unit: 'mm' },
      summary: { component_count: 1 },
    }, manifest, 'processed')

    expect(review.checks.find((check) => check.key === 'components')).toMatchObject({
      level: 'ready',
      count: 1,
    })
  })

  it('preserves diagnostic entity ids for viewer focus', () => {
    const review = buildGeometryReview({
      id: 'geo-1',
      type: 'Geometry',
      info: { length_unit: 'm' },
      summary: { free_edges: ['face-1', { id: 'face-2' }] },
    }, manifest, 'processed')

    expect(review.checks.find((check) => check.key === 'free-edges')).toMatchObject({
      level: 'blocked',
      count: 2,
      entityIds: ['face-1', 'face-2'],
    })
  })
})

describe('formatGeometryNumber', () => {
  it('uses scientific notation for very small geometry dimensions', () => {
    expect(formatGeometryNumber(0.00001)).toBe('1.000e-5')
  })
})
