import type { ResourceDetail } from '../api/client'
import type { ViewerManifest } from '../components/viewer/LazyViewer3D'

export type GeometryCheckLevel = 'ready' | 'warning' | 'blocked' | 'unknown'

export type GeometryCheck = {
  key: string
  label: string
  detail: string
  level: GeometryCheckLevel
  count?: number
  entityIds?: string[]
}

export type GeometryReview = {
  readiness: 'ready' | 'warning' | 'blocked'
  unit: string
  dimensions: [number, number, number] | null
  diagonal: number | null
  checks: GeometryCheck[]
  groupsAreAutogenerated: boolean
}

export function findGeometryValue(value: unknown, aliases: string[]): unknown {
  if (!value || typeof value !== 'object') return undefined
  if (Array.isArray(value)) {
    for (const item of value) {
      const found = findGeometryValue(item, aliases)
      if (found !== undefined) return found
    }
    return undefined
  }
  for (const [key, child] of Object.entries(value)) {
    if (aliases.includes(key.toLowerCase()) && child !== null && child !== '') return child
    const found = findGeometryValue(child, aliases)
    if (found !== undefined) return found
  }
  return undefined
}

export function geometryDisplayValue(value: unknown) {
  if (value === undefined || value === null || value === '') return 'Not reported'
  if (typeof value === 'string' || typeof value === 'number') return String(value)
  if (typeof value === 'object' && value && 'value' in value) {
    const record = value as { value?: unknown; units?: unknown }
    return `${record.value ?? '—'}${record.units ? ` ${record.units}` : ''}`
  }
  return JSON.stringify(value)
}

function numericValue(value: unknown): number | undefined {
  if (typeof value === 'number' && Number.isFinite(value)) return value
  if (typeof value === 'string') {
    const parsed = Number(value)
    return Number.isFinite(parsed) ? parsed : undefined
  }
  if (value && typeof value === 'object' && 'value' in value) {
    return numericValue((value as { value?: unknown }).value)
  }
  return undefined
}

function unitText(value: unknown) {
  if (typeof value === 'string') return value
  if (value && typeof value === 'object') {
    const record = value as { units?: unknown; unit?: unknown }
    const unit = record.units ?? record.unit
    if (typeof unit === 'string') return unit
  }
  return ''
}

function diagnosticCheck(
  detail: ResourceDetail | null,
  key: string,
  label: string,
  aliases: string[],
  severity: 'blocked' | 'warning',
  allowedCount = 0,
): GeometryCheck {
  const raw = findGeometryValue(
    [detail?.summary, detail?.state, detail?.info],
    aliases,
  )
  const entityIds = Array.isArray(raw)
    ? raw.flatMap((item) => {
        if (typeof item === 'string') return [item]
        if (item && typeof item === 'object') {
          const record = item as Record<string, unknown>
          const id = record.id ?? record.entity_id ?? record.name
          return typeof id === 'string' ? [id] : []
        }
        return []
      })
    : []
  const count = entityIds.length > 0 ? entityIds.length : numericValue(raw)
  if (count === undefined) {
    return {
      key,
      label,
      detail: 'Not evaluated by the available Geometry metadata',
      level: 'unknown',
    }
  }
  return count > allowedCount
    ? { key, label, detail: `${count.toLocaleString()} detected`, level: severity, count, entityIds }
    : {
        key,
        label,
        detail: allowedCount > 0
          ? `${count.toLocaleString()} connected component${count === 1 ? '' : 's'}`
          : 'None detected',
        level: 'ready',
        count,
        entityIds,
      }
}

export function buildGeometryReview(
  detail: ResourceDetail | null,
  manifest: ViewerManifest | null,
  status: string,
): GeometryReview {
  const unitValue = findGeometryValue(
    [detail?.info, detail?.simulation_params],
    ['length_unit', 'lengthunit', 'project_length_unit', 'unit'],
  )
  const unit = unitText(unitValue)
  const bounds = manifest?.bounding_box
  const dimensions: [number, number, number] | null = bounds
    ? [
        bounds.max[0] - bounds.min[0],
        bounds.max[1] - bounds.min[1],
        bounds.max[2] - bounds.min[2],
      ]
    : null
  const diagonal = dimensions
    ? Math.hypot(dimensions[0], dimensions[1], dimensions[2])
    : null
  const normalizedStatus = status.toLowerCase()
  const processed = ['completed', 'processed', 'success'].includes(normalizedStatus)
  const errors = detail?.errors ? Object.keys(detail.errors) : []
  const groups = manifest?.groups ?? []
  const groupsAreAutogenerated = groups.length > 0 && groups.every((group) =>
    /(^|_)body\d+_face_\d+$|^face[_ -]?\d+$/i.test(group.name),
  )

  const checks: GeometryCheck[] = [
    {
      key: 'processing',
      label: 'Geometry processing',
      detail: processed ? 'Flow360 processing completed' : `Current state: ${status || 'unknown'}`,
      level: processed ? 'ready' : 'blocked',
    },
    {
      key: 'unit',
      label: 'Physical units',
      detail: unitValue === undefined
        ? 'Length unit must be confirmed before meshing'
        : `Reported as ${geometryDisplayValue(unitValue)}`,
      level: unitValue === undefined ? 'blocked' : 'ready',
    },
    {
      key: 'dimensions',
      label: 'Physical dimensions',
      detail: dimensions
        ? `${dimensions.map((value) => formatGeometryNumber(value)).join(' × ')}${unit ? ` ${unit}` : ''}`
        : 'Bounding box is not available',
      level: dimensions ? 'ready' : 'warning',
    },
    {
      key: 'surfaces',
      label: 'Surface inventory',
      detail: groups.length > 0
        ? `${groups.length.toLocaleString()} renderable surfaces`
        : 'No renderable surface inventory is available',
      level: groups.length > 0 ? 'ready' : 'warning',
    },
    {
      key: 'semantics',
      label: 'CFD surface semantics',
      detail: groupsAreAutogenerated
        ? 'CAD-generated names need engineering classification'
        : groups.length > 0
          ? 'Named surface groups are available for review'
          : 'Surface groups cannot be classified',
      level: groupsAreAutogenerated || groups.length === 0 ? 'warning' : 'ready',
    },
    diagnosticCheck(detail, 'free-edges', 'Open / free edges', [
      'free_edge_count', 'free_edges', 'open_edge_count', 'open_edges',
    ], 'blocked'),
    diagnosticCheck(detail, 'non-manifold', 'Non-manifold edges', [
      'non_manifold_edge_count', 'non_manifold_edges', 'nonmanifold_edge_count',
    ], 'blocked'),
    diagnosticCheck(detail, 'self-intersections', 'Self-intersections', [
      'self_intersection_count', 'self_intersections', 'intersection_count',
    ], 'blocked'),
    diagnosticCheck(detail, 'components', 'Disconnected components', [
      'disconnected_component_count', 'disconnected_components', 'component_count',
    ], 'warning', 1),
    {
      key: 'read-errors',
      label: 'Metadata integrity',
      detail: errors.length === 0
        ? 'No partial-read errors'
        : `${errors.length} Flow360 metadata section(s) failed to load`,
      level: errors.length === 0 ? 'ready' : 'blocked',
    },
  ]

  const readiness = checks.some((check) => check.level === 'blocked')
    ? 'blocked'
    : checks.some((check) => check.level === 'warning' || check.level === 'unknown')
      ? 'warning'
      : 'ready'

  return { readiness, unit, dimensions, diagonal, checks, groupsAreAutogenerated }
}

export function formatGeometryNumber(value: number) {
  const magnitude = Math.abs(value)
  if (magnitude > 0 && (magnitude >= 1e5 || magnitude < 1e-3)) {
    return value.toExponential(3)
  }
  return value.toLocaleString(undefined, { maximumFractionDigits: 4 })
}
