import { describe, expect, it, vi } from 'vitest'
import { createT10Environment, t10ConfiguredPatch, t10Params, t10Progress, validateT10Setup } from './t10'
describe('T10 modular snappy surface meshing', () => {
  it('validates both strategies', () => { expect(validateT10Setup(t10Params(false)).every((check) => check.passed)).toBe(true); expect(validateT10Setup(t10Params(true)).every((check) => check.passed)).toBe(true) })
  it('adds exactly three feature refinements', () => { expect((t10Params(false) as any).meshing.surface_meshing.refinements).toBeUndefined(); expect((t10Params(true) as any).meshing.surface_meshing.refinements.map((item: any) => item.refinement_type)).toEqual(['SnappyBodyRefinement', 'SnappySurfaceRefinement', 'SnappySurfaceEdgeRefinement']) })
  it('preserves canonical remote metadata in configured patches', () => { const patch = t10ConfiguredPatch(true) as any; expect(patch.private_attribute_asset_cache.project_entity_info).toBeUndefined(); expect(patch.private_attribute_asset_cache.use_inhouse_mesher).toBe(false) })
  it('tracks six decisions', () => { expect(t10Progress(['question', 'workflow', 'workflow'])).toBe(33) })
  it('creates a Geometry Project and two SurfaceMesh Drafts', async () => { const createConfiguredDraft = vi.fn(async (projectId: string, input: any) => ({ id: input.name, project_id: projectId })); const result = await createT10Environment({ folderId: 'folder-10', projectName: 'T10 heat sink' }, { stageImport: vi.fn(async () => ({ id: 'import-10' }) as any), approveImport: vi.fn(async () => ({ id: 'import-10' }) as any), runImport: vi.fn(async () => ({ result: { project_id: 'project-10', root_resource_id: 'geometry-10' } }) as any), createConfiguredDraft: createConfiguredDraft as any }, () => undefined, vi.fn(async () => new Response('geometry')) as typeof fetch); expect(createConfiguredDraft.mock.calls.map((call) => call[1].name)).toEqual(['T10 baseline · global snappy defaults', 'T10 variant · feature-aware snappy']); expect(result.projectId).toBe('project-10') })
})
