import { describe, expect, it, vi } from 'vitest'
import { createT12Environment, t12ConfiguredPatch, t12Params, t12Progress, validateT12Setup } from './t12'

describe('T12 liquid flow and gravity', () => {
  it('validates both liquid setups', () => { expect(validateT12Setup(t12Params(false)).every((check) => check.passed)).toBe(true); expect(validateT12Setup(t12Params(true)).every((check) => check.passed)).toBe(true) })
  it('changes only the Fluid models array through the gravity patch', () => { const baseline = t12Params(false) as any; const variant = t12Params(true) as any; expect(baseline.models[0].gravity).toBeUndefined(); expect(variant.models[0].gravity.direction).toEqual([0, 0, -1]); expect(variant.models[0].gravity.magnitude.value).toBe(9.81); expect(variant.operating_condition).toEqual(baseline.operating_condition); expect(variant.meshing).toEqual(baseline.meshing) })
  it('preserves the center Slice in configured patches', () => { const patch = t12ConfiguredPatch(true) as any; expect(patch.private_attribute_asset_cache.project_entity_info.draft_entities).toHaveLength(1); expect(patch.private_attribute_asset_cache.project_entity_info.draft_entities[0].private_attribute_entity_type_name).toBe('Slice') })
  it('tracks six decisions', () => { expect(t12Progress(['question', 'material', 'material'])).toBe(33) })
  it('creates one Geometry Project and two configured Case Drafts', async () => { const createConfiguredDraft = vi.fn(async (projectId: string, input: any) => ({ id: input.name, project_id: projectId })); const result = await createT12Environment({ folderId: 'folder-12', projectName: 'T12 pile' }, { stageImport: vi.fn(async () => ({ id: 'import-12' }) as any), approveImport: vi.fn(async () => ({ id: 'import-12' }) as any), runImport: vi.fn(async () => ({ result: { project_id: 'project-12', root_resource_id: 'geometry-12' } }) as any), createConfiguredDraft: createConfiguredDraft as any }, () => undefined, vi.fn(async () => new Response('geometry')) as typeof fetch); expect(createConfiguredDraft.mock.calls.map((call) => call[1].name)).toEqual(['T12 baseline · water current without gravity', 'T12 variant · water current with Earth gravity']); expect(result.projectId).toBe('project-12') })
})
