import { describe, expect, it, vi } from 'vitest'
import { createT13Environment, t13ConfiguredPatch, t13Params, t13Progress, validateT13Setup } from './t13'

describe('T13 thermally perfect gas', () => {
  it('validates both gas setups', () => { expect(validateT13Setup(t13Params(false)).every((check) => check.passed)).toBe(true); expect(validateT13Setup(t13Params(true)).every((check) => check.passed)).toBe(true) })
  it('changes the frozen species thermodynamics while retaining the flow setup', () => { const baseline = t13Params(false) as any; const variant = t13Params(true) as any; expect(baseline.operating_condition.thermal_state.material.thermally_perfect_gas.species.map((item: any) => item.name)).toEqual(['Air']); expect(variant.operating_condition.thermal_state.material.thermally_perfect_gas.species.map((item: any) => item.name)).toEqual(['N2', 'O2']); expect(variant.operating_condition.velocity_magnitude).toEqual(baseline.operating_condition.velocity_magnitude); expect(variant.meshing).toEqual(baseline.meshing); expect(variant.models).toEqual(baseline.models) })
  it('preserves the center Slice in configured patches', () => { const patch = t13ConfiguredPatch(true) as any; expect(patch.private_attribute_asset_cache.project_entity_info.draft_entities).toHaveLength(1); expect(patch.private_attribute_asset_cache.project_entity_info.draft_entities[0].private_attribute_entity_type_name).toBe('Slice') })
  it('tracks six decisions', () => { expect(t13Progress(['question', 'physics', 'physics'])).toBe(33) })
  it('creates one Geometry Project and two configured Case Drafts', async () => { const createConfiguredDraft = vi.fn(async (projectId: string, input: any) => ({ id: input.name, project_id: projectId })); const result = await createT13Environment({ folderId: 'folder-13', projectName: 'T13 probe' }, { stageImport: vi.fn(async () => ({ id: 'import-13' }) as any), approveImport: vi.fn(async () => ({ id: 'import-13' }) as any), runImport: vi.fn(async () => ({ result: { project_id: 'project-13', root_resource_id: 'geometry-13' } }) as any), createConfiguredDraft: createConfiguredDraft as any }, () => undefined, vi.fn(async () => new Response('geometry')) as typeof fetch); expect(createConfiguredDraft.mock.calls.map((call) => call[1].name)).toEqual(['T13 baseline · constant-gamma hot air', 'T13 variant · frozen N2-O2 NASA-9']); expect(result.projectId).toBe('project-13') })
})
