import { describe, expect, it, vi } from 'vitest'
import { createT14Environment, t14ConfiguredPatch, t14Params, t14Progress, validateT14Setup } from './t14'

describe('T14 RANS turbulence models', () => {
  it('validates both model setups', () => { expect(validateT14Setup(t14Params(false)).every((check) => check.passed)).toBe(true); expect(validateT14Setup(t14Params(true)).every((check) => check.passed)).toBe(true) })
  it('changes solver and compatible freestream quantities but not the experiment', () => { const sa = t14Params(false) as any; const sst = t14Params(true) as any; expect(sa.models[0].turbulence_model_solver.type_name).toBe('SpalartAllmaras'); expect(sst.models[0].turbulence_model_solver.type_name).toBe('kOmegaSST'); expect(sa.models[1].turbulence_quantities.type_name).toBe('ModifiedTurbulentViscosityRatio'); expect(sst.models[1].turbulence_quantities.type_name).toBe('TurbulentIntensityAndTurbulentLengthScale'); expect(sst.meshing).toEqual(sa.meshing); expect(sst.operating_condition).toEqual(sa.operating_condition) })
  it('preserves the Slice and wake Box in configured patches', () => { const entities = (t14ConfiguredPatch(true) as any).private_attribute_asset_cache.project_entity_info.draft_entities; expect(entities).toHaveLength(2); expect(entities.map((item: any) => item.private_attribute_entity_type_name).sort()).toEqual(['Box', 'Slice']) })
  it('tracks six decisions', () => { expect(t14Progress(['question', 'closure', 'closure'])).toBe(33) })
  it('creates one Geometry Project and two configured Case Drafts', async () => { const createConfiguredDraft = vi.fn(async (projectId: string, input: any) => ({ id: input.name, project_id: projectId })); const result = await createT14Environment({ folderId: 'folder-14', projectName: 'T14 rear step' }, { stageImport: vi.fn(async () => ({ id: 'import-14' }) as any), approveImport: vi.fn(async () => ({ id: 'import-14' }) as any), runImport: vi.fn(async () => ({ result: { project_id: 'project-14', root_resource_id: 'geometry-14' } }) as any), createConfiguredDraft: createConfiguredDraft as any }, () => undefined, vi.fn(async () => new Response('geometry')) as typeof fetch); expect(createConfiguredDraft.mock.calls.map((call) => call[1].name)).toEqual(['T14 baseline · Spalart-Allmaras rear-step wake', 'T14 variant · k-omega SST rear-step wake']); expect(result.projectId).toBe('project-14') })
})
