import { describe, expect, it, vi } from 'vitest'
import { createT15Environment, t15ConfiguredPatch, t15Params, t15Progress, validateT15Setup, type T15Mode } from './t15'

describe('T15 transition and DDES decision', () => {
  const modes: T15Mode[] = ['rans', 'transition', 'ddes']
  it('validates all three model branches', () => { for (const mode of modes) expect(validateT15Setup(t15Params(mode)).every((check) => check.passed)).toBe(true) })
  it('keeps SST while adding the branch-specific method', () => { const rans = t15Params('rans') as any; const transition = t15Params('transition') as any; const ddes = t15Params('ddes') as any; expect(rans.models[0].turbulence_model_solver.type_name).toBe('kOmegaSST'); expect(transition.models[0].transition_model_solver.type_name).toBe('AmplificationFactorTransport'); expect(transition.models[0].transition_model_solver.N_crit).toBeCloseTo(8.14989219); expect(ddes.models[0].turbulence_model_solver.hybrid_model).toEqual({ shielding_function: 'DDES', grid_size_for_LES: 'shearLayerAdapted' }); expect(ddes.time_stepping.type_name).toBe('Unsteady') })
  it('preserves the Slice and separated-flow Box in configured patches', () => { for (const mode of modes) { const entities = (t15ConfiguredPatch(mode) as any).private_attribute_asset_cache.project_entity_info.draft_entities; expect(entities.map((item: any) => item.private_attribute_entity_type_name).sort()).toEqual(['Box', 'Slice']) } })
  it('tracks six decisions', () => { expect(t15Progress(['question', 'models', 'models'])).toBe(33) })
  it('creates one Geometry Project and three configured Case Drafts', async () => { const createConfiguredDraft = vi.fn(async (projectId: string, input: any) => ({ id: input.name, project_id: projectId })); const result = await createT15Environment({ folderId: 'folder-15', projectName: 'T15 high lift' }, { stageImport: vi.fn(async () => ({ id: 'import-15' }) as any), approveImport: vi.fn(async () => ({ id: 'import-15' }) as any), runImport: vi.fn(async () => ({ result: { project_id: 'project-15', root_resource_id: 'geometry-15' } }) as any), createConfiguredDraft: createConfiguredDraft as any }, () => undefined, vi.fn(async () => new Response('geometry')) as typeof fetch); expect(createConfiguredDraft.mock.calls.map((call) => call[1].name)).toEqual(['T15 baseline · fully turbulent SST', 'T15 branch · SST with AFT transition', 'T15 branch · unsteady SST-DDES']); expect(result.additionalDrafts).toHaveLength(1) })
})
