import { describe, expect, it, vi } from 'vitest'
import { createT16Environment, t16ConfiguredPatch, t16Params, t16Progress, validateT16Setup, type T16Mode } from './t16'

describe('T16 numerical diagnostics', () => {
  const modes: T16Mode[] = ['recovery', 'accuracy', 'krylov']
  it('validates all three numerical stages', () => { for (const mode of modes) expect(validateT16Setup(t16Params(mode)).every((check) => check.passed)).toBe(true) })
  it('stages recovery, accuracy, and Krylov/SLAU2 deliberately', () => { const recovery = t16Params('recovery') as any; const accuracy = t16Params('accuracy') as any; const krylov = t16Params('krylov') as any; expect(recovery.models[0].navier_stokes_solver.order_of_accuracy).toBe(1); expect(accuracy.models[0].navier_stokes_solver.order_of_accuracy).toBe(2); expect(krylov.models[0].navier_stokes_solver.linear_solver.type_name).toBe('KrylovLinearSolver'); expect(krylov.models[0].navier_stokes_solver.riemann_solver).toEqual({ type_name: 'SLAU2', jacobian: 'Roe' }) })
  it('preserves the diagnostic Slice and wake Box', () => { for (const mode of modes) { const entities = (t16ConfiguredPatch(mode) as any).private_attribute_asset_cache.project_entity_info.draft_entities; expect(entities.map((item: any) => item.private_attribute_entity_type_name).sort()).toEqual(['Box', 'Slice']) } })
  it('tracks six decisions', () => { expect(t16Progress(['symptom', 'evidence', 'evidence'])).toBe(33) })
  it('creates one Geometry Project and three configured Case Drafts', async () => { const createConfiguredDraft = vi.fn(async (projectId: string, input: any) => ({ id: input.name, project_id: projectId })); const result = await createT16Environment({ folderId: 'folder-16', projectName: 'T16 numerics' }, { stageImport: vi.fn(async () => ({ id: 'import-16' }) as any), approveImport: vi.fn(async () => ({ id: 'import-16' }) as any), runImport: vi.fn(async () => ({ result: { project_id: 'project-16', root_resource_id: 'geometry-16' } }) as any), createConfiguredDraft: createConfiguredDraft as any }, () => undefined, vi.fn(async () => new Response('geometry')) as typeof fetch); expect(createConfiguredDraft.mock.calls.map((call) => call[1].name)).toEqual(['T16 stage 1 · conservative recovery', 'T16 stage 2 · restored second order', 'T16 stage 3 · steady Krylov and SLAU2']); expect(result.additionalDrafts).toHaveLength(1) })
})
