import { describe, expect, it, vi } from 'vitest'
import { createT17Environment, t17ConfiguredPatch, t17Params, t17Progress, validateT17Setup, type T17Mode } from './t17'

describe('T17 initialization and restart', () => {
  const modes: T17Mode[] = ['source', 'uniform', 'expression', 'restart']
  it('validates every initialization branch', () => { for (const mode of modes) expect(validateT17Setup(t17Params(mode)).every((check) => check.passed)).toBe(true) })
  it('keeps new-field and restart semantics separate', () => { const source = t17Params('source') as any; const expression = t17Params('expression') as any; const restart = t17Params('restart') as any; expect(source.models[0].initial_condition.type_name).toBe('NavierStokesInitialCondition'); expect(expression.models[0].initial_condition.constants.wakeDeficit).toBe('0.15'); expect(restart.models[0].initial_condition.type_name).toBe('NavierStokesModifiedRestartSolution'); expect(restart.models[0].initial_condition.constants.deltaAlpha).toBe('0.06981317008'); expect(restart.models[0].initial_condition).not.toHaveProperty('case_id') })
  it('preserves the registered comparison Slice', () => { for (const mode of modes) { const entities = (t17ConfiguredPatch(mode) as any).private_attribute_asset_cache.project_entity_info.draft_entities; expect(entities.map((item: any) => item.private_attribute_entity_type_name)).toEqual(['Slice']) } })
  it('tracks six decisions', () => { expect(t17Progress(['decision', 'expressions', 'expressions'])).toBe(33) })
  it('creates three valid pre-run Drafts and no parentless restart Draft', async () => { const createConfiguredDraft = vi.fn(async (projectId: string, input: any) => ({ id: input.name, project_id: projectId })); const result = await createT17Environment({ folderId: 'folder-17', projectName: 'T17 initialization' }, { stageImport: vi.fn(async () => ({ id: 'import-17' }) as any), approveImport: vi.fn(async () => ({ id: 'import-17' }) as any), runImport: vi.fn(async () => ({ result: { project_id: 'project-17', root_resource_id: 'geometry-17' } }) as any), createConfiguredDraft: createConfiguredDraft as any }, () => undefined, vi.fn(async () => new Response('geometry')) as typeof fetch); expect(createConfiguredDraft.mock.calls.map((call) => call[1].name)).toEqual(['T17 source · 8° uniform start', 'T17 target · 12° uniform start', 'T17 target · 12° expression seed']); expect(createConfiguredDraft.mock.calls.flatMap((call) => JSON.stringify(call[1]))).not.toContain('NavierStokesModifiedRestartSolution'); expect(result.additionalDrafts).toHaveLength(1) })
})
