package aicreate

import (
	_ "embed"
	"fmt"
	"io"
)

// cylinderBREP is an exact analytic B-rep generated by CadQuery 2.6.1 with
// OpenCascade 7.8.1 and validated by reading it back through the same CAD
// kernel. It contains one cylindrical and two planar faces, not triangles.
//
//go:embed assets/cylinder.brep
var cylinderBREP []byte

func WriteCylinderBREP(w io.Writer, geometry Geometry) error {
	if geometry.Kind != "cylinder" || geometry.DiameterM != 1 || geometry.SpanM != 1 {
		return fmt.Errorf("the embedded exact CAD template supports only a 1 m diameter × 1 m span cylinder")
	}
	if geometry.Representation != "analytic-brep" || geometry.Format != "brep" || !geometry.Validated {
		return fmt.Errorf("cylinder CAD provenance is incomplete")
	}
	_, err := w.Write(cylinderBREP)
	return err
}
