import { AlertTriangle, ArrowLeft, ArrowRight, Boxes, Check, CheckCircle2, Cloud, Download, GitCompare, Grid3X3, Layers3, RotateCcw, ShieldCheck, Sparkles } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import type { Flow360Status } from '../api/client'
import { api } from '../api/client'
import TopBar from '../components/TopBar'
import TutorialEnvironmentBuilder from '../components/TutorialEnvironmentBuilder'
import { TutorialConceptBridge, TutorialDerivations, TutorialEvidenceRubric, TutorialFailureModes, TutorialPrediction, TutorialTransferCheck } from '../components/TutorialTeachingBlocks'
import { createT10Environment, t10Evidence, t10ParameterCards, t10Params, t10Pedagogy, t10Progress, t10Steps, validateT10Setup } from '../tutorials/t10'

const storageKey = 'vibesim.tutorial.T10.completed'
function readProgress() { try { const value = JSON.parse(window.localStorage.getItem(storageKey) || '[]'); return Array.isArray(value) ? value.filter((item): item is string => typeof item === 'string') : [] } catch { return [] } }
function downloadJSON(params: Record<string, unknown>, feature: boolean) { const blob = new Blob([`${JSON.stringify(params, null, 2)}\n`], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `T10-${feature ? 'feature-aware' : 'global'}-snappy.simulation.json`; anchor.click(); URL.revokeObjectURL(url) }
export function HeatSinkVisual({ feature = false }: { feature?: boolean }) { return <svg className="tutorial-airfoil" viewBox="0 0 720 320" role="img" aria-label={`${feature ? 'Feature-aware' : 'Global-only'} heat-sink surface mesh`}><rect x="95" y="220" width="530" height="35" rx="4" fill="#cbd69f" stroke="#526239" strokeWidth="2"/>{[130,210,290,370,450,530].map((x) => <rect key={x} x={x} y="75" width="24" height="145" fill={feature ? '#dce9aa' : '#e7eadc'} stroke="#526239" strokeWidth="2"/>)}{feature && [130,154,210,234,290,314,370,394,450,474,530,554].map((x) => <path key={x} d={`M${x} 75 V220`} stroke="#d65f35" strokeWidth="3"/>)}{[170,250,330,410,490].map((x) => <path key={x} d={`M${x} 140 h28`} stroke="#79a4ad" strokeWidth="3" markerEnd="url(#mesh-arrow)"/>)}<defs><marker id="mesh-arrow" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L0,6 L7,3 z" fill="#79a4ad"/></marker></defs><text x="105" y="285">6 fins · 4 mm thick · 5 channels · 14 mm wide</text><text x="465" y="55">{feature ? 'local edge + face refinement' : 'global spacing only'}</text></svg> }

export default function T10TutorialPage() {
  const [status, setStatus] = useState<Flow360Status | null>(null); const [stepIndex, setStepIndex] = useState(0); const [completed, setCompleted] = useState<string[]>(readProgress); const [feature, setFeature] = useState(false); const [checksVisible, setChecksVisible] = useState(false); const [reviewed, setReviewed] = useState<string[]>([])
  const params = useMemo(() => t10Params(feature), [feature]); const checks = useMemo(() => validateT10Setup(params), [params]); const step = t10Steps[stepIndex]
  useEffect(() => { api.flow360Status().then(setStatus).catch(() => setStatus({ available: false })) }, []); useEffect(() => window.localStorage.setItem(storageKey, JSON.stringify(completed)), [completed])
  const finishStep = () => { setCompleted((current) => current.includes(step.id) ? current : [...current, step.id]); setStepIndex((current) => Math.min(current + 1, t10Steps.length - 1)) }
  const lesson = () => { switch (step.id) {
    case 'question': return <><div className="lesson-kicker"><Sparkles size={15}/> Engineering decision</div><h1>Will the surface mesh keep every cooling passage open?</h1><p className="lesson-lead">The supplied heat sink has six 4 mm fins and five 14 mm channels. Losing a fin, rounding a root, or bridging a passage changes wetted area, hydraulic diameter, pressure drop, and heat transfer before volume meshing begins.</p><div className="lesson-decision-card"><span>DECISION</span><strong>Are global snappy defaults sufficient?</strong><p>Accept them only if topology, dimensions, sharp features, and quality pass. Otherwise add controls tied to the failing geometric risk.</p></div><div className="lesson-objectives"><div><Layers3/><span><strong>Separate meshing stages</strong>Configure the surface without hiding later volume decisions.</span></div><div><Grid3X3/><span><strong>Spend cells locally</strong>Match refinement type to body, face, or edge risk.</span></div><div><ShieldCheck/><span><strong>Measure evidence</strong>Check topology, dimensions, quality, and cost.</span></div></div><TutorialConceptBridge cfd={t10Pedagogy.cfdConcepts} flow360={t10Pedagogy.flow360Concepts}/></>
    case 'workflow': return <><div className="lesson-kicker"><Boxes size={15}/> Modular snappy pipeline</div><h1>Read the surface mesher as four coupled stages.</h1><p className="lesson-lead">Castellating creates octree cells, snapping moves them toward CAD, smoothing controls distortion, and QualityMetrics decides which defects are unacceptable. ModularMeshingWorkflow keeps this surface stage separate from future volume settings.</p><div className="aircraft-stage"><HeatSinkVisual feature={feature}/></div><div className="geometry-assumptions"><div><span>CASTELLATE</span><strong>{feature ? '2' : '1'} cells</strong><small>between levels</small></div><div><span>SNAP</span><strong>{feature ? 'Strict' : 'Standard'}</strong><small>region behavior</small></div><div><span>QUALITY</span><strong>70°</strong><small>non-orthogonality</small></div></div><div className="lesson-callout warning"><AlertTriangle size={17}/><p><strong>Pipeline rule</strong>Strict snapping is not an acceptance result. The generated surface still needs topology, dimensional, and quality review.</p></div></>
    case 'spacing': return <><div className="lesson-kicker"><Grid3X3 size={15}/> Octree resolution</div><h1>Turn feature sizes into effective mesh levels.</h1><p className="lesson-lead">Snappy uses discrete factor-of-two octree levels. T10 chooses level-aligned values so the requested and effective spacing agree, then evaluates samples across the narrow channel and thin fin.</p><div className="parameter-learning-grid">{t10ParameterCards.map((item) => <article key={item.label}><div><span className={`provenance ${item.provenance}`}>{item.provenance}</span><strong>{item.label}</strong></div><b>{item.value}</b><p>{item.why}</p></article>)}</div><TutorialDerivations items={t10Pedagogy.derivations}/><button className="lesson-validate-button" onClick={() => setChecksVisible(true)}><ShieldCheck size={16}/> Validate the snappy setup in the browser</button>{checksVisible && <div className="setup-checks">{checks.map((check) => <div className={check.passed ? 'passed' : 'failed'} key={check.id}>{check.passed ? <CheckCircle2 size={17}/> : <AlertTriangle size={17}/>}<span><strong>{check.label}</strong><small>{check.detail}</small></span></div>)}</div>}</>
    case 'experiment': return <><div className="lesson-kicker"><GitCompare size={15}/> Controlled mesh experiment</div><h1>Add controls only where geometry proves they are needed.</h1><p className="lesson-lead">The variant adds BodyRefinement for the component, RegionRefinement for fin faces and proximity, and SurfaceEdgeRefinement for roots and tips. CAD, global defaults, smoothing, quality limits, and farfield stay fixed.</p><TutorialPrediction experiment={t10Pedagogy.experiments[0]}/><div className="alpha-experiment"><div className="alpha-control" role="group" aria-label="Snappy refinement strategy"><button className={!feature ? 'active' : ''} onClick={() => setFeature(false)}><span>Baseline</span><strong>Global defaults</strong></button><button className={feature ? 'active' : ''} onClick={() => setFeature(true)}><span>Variant</span><strong>Feature aware</strong></button></div><div className="alpha-visual"><Grid3X3 size={82} strokeWidth={1.1}/><span>{feature ? 'body + region + edge' : 'global octree levels'}</span></div><div className="semantic-diff"><p className="eyebrow">REFINEMENT SET</p><div><code>surface_meshing.refinements</code><span>0</span><ArrowRight size={14}/><strong>{feature ? '3' : '0'}</strong></div><small>{feature ? 'Whole-body bounds, fin proximity, and sharp-edge distance fields are active.' : 'The global-only control case is selected.'}</small></div></div><TutorialFailureModes items={t10Pedagogy.failureModes}/><button className="lesson-secondary-button" onClick={() => downloadJSON(params, feature)}><Download size={15}/> Download selected setup</button></>
    case 'evidence': return <><div className="lesson-kicker"><ShieldCheck size={15}/> Surface-mesh evidence contract</div><h1>Measure geometry preservation and mesh quality together.</h1><p className="lesson-lead">Inspect both meshes in identical sections. Record components, holes, non-manifold edges, fin thickness, channel width, quality maxima, and surface-cell count before selecting a strategy for volume meshing.</p><div className="evidence-checklist">{t10Evidence.map((item) => { const selected = reviewed.includes(item.title); return <button className={selected ? 'reviewed' : ''} key={item.title} onClick={() => setReviewed((current) => selected ? current.filter((value) => value !== item.title) : [...current, item.title])}><span className="evidence-check">{selected && <Check size={15}/>}</span><span><strong>{item.title}</strong><small>{item.detail}</small></span></button> })}</div><div className={`lesson-callout ${reviewed.length === t10Evidence.length ? 'success' : ''}`}>{reviewed.length === t10Evidence.length ? <CheckCircle2 size={17}/> : <AlertTriangle size={17}/>}<p><strong>{reviewed.length}/5 reviewed</strong>{reviewed.length === t10Evidence.length ? 'The surface-mesh acceptance contract is complete.' : 'Review every requirement before creating the environment.'}</p></div><TutorialEvidenceRubric items={t10Pedagogy.evidenceRubric}/></>
    default: return <><div className="lesson-kicker"><Cloud size={15}/> Create the snappy mesh environment</div><h1>Create both configured SurfaceMesh Drafts from the supplied heat sink.</h1><p className="lesson-lead">The app uploads the lightweight heat-sink Geometry, creates one Project, and synchronizes global-only and feature-aware snappy SurfaceMesh Drafts with explicit controls and quality limits.</p><div className="run-readiness-card"><div className="run-ready-icon"><CheckCircle2 size={30}/></div><div><span>CONFIGURATION STATUS</span><strong>Both snappy surface strategies validated</strong><p>No surface or volume mesh is submitted; you retain compute control in the Project workspace.</p></div></div><TutorialTransferCheck items={t10Pedagogy.transferQuestions}/><TutorialEnvironmentBuilder status={status} tutorialId="T10" defaultProjectName="Tutorial T10 · snappy heat-sink mesh" heading="Build the T10 snappy surface-mesh comparison" description="The app uploads the bundled heat sink and creates global-only and feature-aware SurfaceMesh Drafts." configurationSummary="ModularMeshingWorkflow, octree spacing, Body/Region/SurfaceEdge refinements, snap and smooth controls, explicit quality metrics" draftKind="SurfaceMesh" baselineValue="Global snappy defaults" variantValue="Feature-aware snappy controls" successDescription="Both SurfaceMesh Draft parameter sets are synced. No surface or volume mesh computation has been submitted." createEnvironment={createT10Environment}/></>
  } }
  return <div className="tutorial-player-page"><TopBar status={status} title="Guided tutorial · T10"/><aside className="tutorial-outline"><Link className="tutorial-back" to="/tutorials"><ArrowLeft size={14}/> All tutorials</Link><div className="tutorial-outline-title"><span>T10</span><h2>Modular snappy surface meshing</h2><small>Surface meshing · 22–28 min</small></div><div className="tutorial-progress"><div><span>Progress</span><strong>{t10Progress(completed)}%</strong></div><progress value={t10Progress(completed)} max="100"/></div><nav aria-label="Tutorial steps">{t10Steps.map((item, index) => <button key={item.id} className={`${index === stepIndex ? 'active' : ''} ${completed.includes(item.id) ? 'complete' : ''}`} onClick={() => setStepIndex(index)}><span>{completed.includes(item.id) ? <Check size={13}/> : item.label}</span><div><strong>{item.title}</strong><small>{item.summary}</small></div></button>)}</nav><button className="tutorial-reset" onClick={() => { setCompleted([]); setStepIndex(0); setReviewed([]); setChecksVisible(false); setFeature(false) }}><RotateCcw size={13}/> Reset progress</button></aside><main className="tutorial-lesson"><div className="lesson-content">{lesson()}</div><footer className="lesson-footer"><button className="lesson-previous" disabled={stepIndex === 0} onClick={() => setStepIndex((current) => Math.max(0, current - 1))}><ArrowLeft size={15}/> Previous</button><span>Step {stepIndex + 1} of {t10Steps.length}</span>{stepIndex < t10Steps.length - 1 ? <button className="lesson-next" onClick={finishStep}>Complete & continue <ArrowRight size={15}/></button> : <button className="lesson-next" onClick={() => setCompleted((current) => current.includes(step.id) ? current : [...current, step.id])}><Check size={15}/> Mark tutorial complete</button>}</footer></main></div>
}
