import { AlertTriangle, ArrowDown, ArrowLeft, ArrowRight, Check, CheckCircle2, Cloud, Download, Droplets, Gauge, GitCompare, RotateCcw, ShieldCheck, Sparkles } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import type { Flow360Status } from '../api/client'
import { api } from '../api/client'
import TopBar from '../components/TopBar'
import TutorialEnvironmentBuilder from '../components/TutorialEnvironmentBuilder'
import { TutorialConceptBridge, TutorialDerivations, TutorialEvidenceRubric, TutorialFailureModes, TutorialPrediction, TutorialTransferCheck } from '../components/TutorialTeachingBlocks'
import { createT12Environment, t12Evidence, t12ParameterCards, t12Params, t12Pedagogy, t12Progress, t12Steps, validateT12Setup } from '../tutorials/t12'

const storageKey = 'vibesim.tutorial.T12.completed'
function readProgress() { try { const parsed = JSON.parse(window.localStorage.getItem(storageKey) || '[]'); return Array.isArray(parsed) ? parsed.filter((item): item is string => typeof item === 'string') : [] } catch { return [] } }
function downloadJSON(params: Record<string, unknown>, gravity: boolean) { const blob = new Blob([`${JSON.stringify(params, null, 2)}\n`], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `T12-water-${gravity ? 'gravity' : 'baseline'}.simulation.json`; anchor.click(); URL.revokeObjectURL(url) }

function PileVisual({ gravity }: { gravity: boolean }) {
  return <svg className="tutorial-aircraft" viewBox="0 0 760 360" role="img" aria-label="Four metre submerged pile with current and gravity directions"><defs><linearGradient id="t12-water" x1="0" x2="1"><stop stopColor="#d9eef4"/><stop offset="1" stopColor="#91cad8"/></linearGradient></defs><rect x="45" y="38" width="670" height="278" rx="24" fill="url(#t12-water)" opacity=".6"/><rect x="362" y="62" width="36" height="232" rx="18" fill="#657266"/><path d="M95 180 H300" stroke="#287c96" strokeWidth="8"/><path d="M285 163 L315 180 L285 197" fill="none" stroke="#287c96" strokeWidth="8"/><text x="95" y="155">2 m/s water current</text><line x1="422" y1="62" x2="470" y2="62" stroke="#526239"/><line x1="422" y1="294" x2="470" y2="294" stroke="#526239"/><line x1="452" y1="62" x2="452" y2="294" stroke="#526239"/><text x="480" y="183">4 m</text>{gravity && <><line x1="610" y1="90" x2="610" y2="230" stroke="#d65f35" strokeWidth="6"/><path d="M592 212 L610 242 L628 212" fill="none" stroke="#d65f35" strokeWidth="6"/><text x="565" y="75">g = 9.81 m/s²</text><text x="530" y="270">pressure increases downward</text></>}</svg>
}

export default function T12TutorialPage() {
  const [status, setStatus] = useState<Flow360Status | null>(null); const [stepIndex, setStepIndex] = useState(0); const [completed, setCompleted] = useState<string[]>(readProgress); const [gravity, setGravity] = useState(false); const [checksVisible, setChecksVisible] = useState(false); const [reviewed, setReviewed] = useState<string[]>([])
  const params = useMemo(() => t12Params(gravity), [gravity]); const checks = useMemo(() => validateT12Setup(params), [params]); const step = t12Steps[stepIndex]
  useEffect(() => { api.flow360Status().then(setStatus).catch(() => setStatus({ available: false })) }, []); useEffect(() => window.localStorage.setItem(storageKey, JSON.stringify(completed)), [completed])
  const finishStep = () => { setCompleted((current) => current.includes(step.id) ? current : [...current, step.id]); setStepIndex((current) => Math.min(current + 1, t12Steps.length - 1)) }
  const lesson = () => {
    switch (step.id) {
      case 'question': return <><div className="lesson-kicker"><Sparkles size={15}/> Engineering decision</div><h1>How much of the pressure on a submerged pile comes from depth?</h1><p className="lesson-lead">A 4 m vertical pile sits in a 2 m/s water current. Current produces separation and drag; gravity produces a pressure gradient with elevation. The structural pressure field contains both contributions.</p><div className="lesson-decision-card"><span>DECISION</span><strong>Can gravity be omitted from the load interpretation?</strong><p>Compare ρgΔz with ½ρU² first. Here the hydrostatic span is 19.62 times the dynamic-pressure scale, so raw pressure cannot be treated as current-only loading.</p></div><div className="aircraft-stage"><PileVisual gravity={gravity}/></div><TutorialConceptBridge cfd={t12Pedagogy.cfdConcepts} flow360={t12Pedagogy.flow360Concepts}/></>
      case 'material': return <><div className="lesson-kicker"><Droplets size={15}/> Liquid reference state</div><h1>Water is a material model, not slow air.</h1><p className="lesson-lead">LiquidOperatingCondition carries Water density and viscosity together with the 2 m/s physical and reference velocities. The pinned Flow360 release then applies liquid-compatible scaling and output rules.</p><div className="parameter-learning-grid">{t12ParameterCards.map((item) => <article key={item.label}><div><span className={`provenance ${item.provenance === 'provided' ? 'provided' : 'adapted'}`}>{item.provenance}</span><strong>{item.label}</strong></div><b>{item.value}</b><p>{item.why}</p></article>)}</div><div className="lesson-callout warning"><AlertTriangle size={17}/><p><strong>Boundary support in Flow360 25.10</strong>LiquidOperatingCondition rejects Inflow and Outflow models. T12 therefore uses AutomatedFarfield plus Freestream around a fully submerged body.</p></div><button className="lesson-validate-button" onClick={() => setChecksVisible(true)}><ShieldCheck size={16}/> Validate the liquid Case in the browser</button>{checksVisible && <div className="setup-checks">{checks.map((check) => <div className={check.passed ? 'passed' : 'failed'} key={check.id}>{check.passed ? <CheckCircle2 size={17}/> : <AlertTriangle size={17}/>}<span><strong>{check.label}</strong><small>{check.detail}</small></span></div>)}</div>}</>
      case 'scales': return <><div className="lesson-kicker"><Gauge size={15}/> Pre-solve scale analysis</div><h1>Calculate both pressure scales before opening a contour.</h1><p className="lesson-lead">The pile Reynolds number predicts turbulent separated crossflow. Dynamic pressure scales the current disturbance, while hydrostatic head sets the much larger pressure change between the top and bottom.</p><TutorialDerivations items={t12Pedagogy.derivations}/><div className="geometry-assumptions"><div><span>REYNOLDS NUMBER</span><strong>3.99 × 10⁵</strong><small>ρUD/μ</small></div><div><span>DYNAMIC PRESSURE</span><strong>2.00 kPa</strong><small>½ρU²</small></div><div><span>HYDROSTATIC SPAN</span><strong>39.24 kPa</strong><small>ρgΔz</small></div></div></>
      case 'experiment': return <><div className="lesson-kicker"><GitCompare size={15}/> Controlled physics experiment</div><h1>Add one body force and predict its pressure signature.</h1><p className="lesson-lead">The variant adds Gravity inside Fluid with direction [0, 0, −1]. Water properties, 2 m/s current, pile, farfield, wall, mesh, steady steps, and output fields do not change.</p><TutorialPrediction experiment={t12Pedagogy.experiments[0]}/><div className="alpha-experiment"><div className="alpha-control" role="group" aria-label="Gravity model"><button className={!gravity ? 'active' : ''} onClick={() => setGravity(false)}><span>Baseline</span><strong>Gravity off</strong></button><button className={gravity ? 'active' : ''} onClick={() => setGravity(true)}><span>Variant</span><strong>Earth gravity</strong></button></div><div className="alpha-visual">{gravity ? <ArrowDown size={82} strokeWidth={1.1}/> : <Droplets size={82} strokeWidth={1.1}/>}<span>{gravity ? 'dp/dz ≈ −9810 Pa/m' : 'no hydrostatic slope'}</span></div><div className="semantic-diff"><p className="eyebrow">PHYSICS DIFF</p><div><code>Fluid.gravity</code><span>absent</span><ArrowRight size={14}/><strong>{gravity ? '9.81 m/s², −z' : 'absent'}</strong></div><small>{gravity ? 'The water body force is active globally.' : 'The controlled baseline remains selected.'}</small></div></div><TutorialFailureModes items={t12Pedagogy.failureModes}/><button className="lesson-secondary-button" onClick={() => downloadJSON(params, gravity)}><Download size={15}/> Download selected setup</button></>
      case 'evidence': return <><div className="lesson-kicker"><ShieldCheck size={15}/> Pressure and load evidence</div><h1>Remove the depth trend before assigning pressure to the current.</h1><p className="lesson-lead">Fit pressure versus z away from the pile, verify its slope, and subtract that same hydrostatic reference from surface pressure. Then compare wake pressure, drag, vertical force, y+, mesh sensitivity, residuals, and load stability.</p><div className="evidence-checklist">{t12Evidence.map((item) => { const selected = reviewed.includes(item.title); return <button className={selected ? 'reviewed' : ''} key={item.title} onClick={() => setReviewed((current) => selected ? current.filter((value) => value !== item.title) : [...current, item.title])}><span className="evidence-check">{selected && <Check size={15}/>}</span><span><strong>{item.title}</strong><small>{item.detail}</small></span></button> })}</div><div className={`lesson-callout ${reviewed.length === t12Evidence.length ? 'success' : ''}`}>{reviewed.length === t12Evidence.length ? <CheckCircle2 size={17}/> : <AlertTriangle size={17}/>}<p><strong>{reviewed.length}/5 reviewed</strong>{reviewed.length === t12Evidence.length ? 'The liquid-gravity evidence contract is complete.' : 'Review every requirement before creating the environment.'}</p></div><TutorialEvidenceRubric items={t12Pedagogy.evidenceRubric}/></>
      default: return <><div className="lesson-kicker"><Cloud size={15}/> Create the liquid-gravity environment</div><h1>Create both configured Case Drafts from the supplied pile.</h1><p className="lesson-lead">The app uploads the lightweight vertical-pile Geometry, creates one Project, registers the pressure Slice, and synchronizes gravity-off and Earth-gravity Case Drafts with complete Water, mesh, boundary, solver, and output parameters.</p><div className="run-readiness-card"><div className="run-ready-icon"><CheckCircle2 size={30}/></div><div><span>CONFIGURATION STATUS</span><strong>Both liquid Case setups validated</strong><p>No mesh or solver Case is submitted; compute remains under your control in the Project workspace.</p></div></div><TutorialTransferCheck items={t12Pedagogy.transferQuestions}/><TutorialEnvironmentBuilder status={status} tutorialId="T12" defaultProjectName="Tutorial T12 · submerged pile gravity" heading="Build the T12 water-and-gravity comparison" description="The app uploads the bundled submerged pile and creates gravity-off and Earth-gravity Case Drafts." configurationSummary="Water, LiquidOperatingCondition at 2 m/s, AutomatedFarfield, pile Wall, optional 9.81 m/s² Gravity, dimensional pressure outputs" draftKind="Case" baselineValue="Water current without gravity" variantValue="Water current with Earth gravity" successDescription="Both Case Draft parameter sets are synced. No surface mesh, volume mesh, or solver Case has been submitted." createEnvironment={createT12Environment}/></>
    }
  }
  return <div className="tutorial-player-page"><TopBar status={status} title="Guided tutorial · T12"/><aside className="tutorial-outline"><Link className="tutorial-back" to="/tutorials"><ArrowLeft size={14}/> All tutorials</Link><div className="tutorial-outline-title"><span>T12</span><h2>Water flow with gravity</h2><small>Liquid CFD · 20–25 min</small></div><div className="tutorial-progress"><div><span>Progress</span><strong>{t12Progress(completed)}%</strong></div><progress value={t12Progress(completed)} max="100"/></div><nav aria-label="Tutorial steps">{t12Steps.map((item, index) => <button key={item.id} className={`${index === stepIndex ? 'active' : ''} ${completed.includes(item.id) ? 'complete' : ''}`} onClick={() => setStepIndex(index)}><span>{completed.includes(item.id) ? <Check size={13}/> : item.label}</span><div><strong>{item.title}</strong><small>{item.summary}</small></div></button>)}</nav><button className="tutorial-reset" onClick={() => { setCompleted([]); setStepIndex(0); setReviewed([]); setChecksVisible(false); setGravity(false) }}><RotateCcw size={13}/> Reset progress</button></aside><main className="tutorial-lesson"><div className="lesson-content">{lesson()}</div><footer className="lesson-footer"><button className="lesson-previous" disabled={stepIndex === 0} onClick={() => setStepIndex((current) => Math.max(0, current - 1))}><ArrowLeft size={15}/> Previous</button><span>Step {stepIndex + 1} of {t12Steps.length}</span>{stepIndex < t12Steps.length - 1 ? <button className="lesson-next" onClick={finishStep}>Complete & continue <ArrowRight size={15}/></button> : <button className="lesson-next" onClick={() => setCompleted((current) => current.includes(step.id) ? current : [...current, step.id])}><Check size={15}/> Mark tutorial complete</button>}</footer></main></div>
}
