import { AlertTriangle, ArrowLeft, ArrowRight, Check, CheckCircle2, Cloud, Download, Flame, Gauge, GitCompare, RotateCcw, ShieldCheck, Sparkles, Thermometer } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import type { Flow360Status } from '../api/client'
import { api } from '../api/client'
import TopBar from '../components/TopBar'
import TutorialEnvironmentBuilder from '../components/TutorialEnvironmentBuilder'
import { TutorialConceptBridge, TutorialDerivations, TutorialEvidenceRubric, TutorialFailureModes, TutorialPrediction, TutorialTransferCheck } from '../components/TutorialTeachingBlocks'
import { createT13Environment, t13Evidence, t13ParameterCards, t13Params, t13Pedagogy, t13Progress, t13Steps, validateT13Setup } from '../tutorials/t13'

const storageKey = 'vibesim.tutorial.T13.completed'
function readProgress() { try { const parsed = JSON.parse(window.localStorage.getItem(storageKey) || '[]'); return Array.isArray(parsed) ? parsed.filter((item): item is string => typeof item === 'string') : [] } catch { return [] } }
function downloadJSON(params: Record<string, unknown>, mixture: boolean) { const blob = new Blob([`${JSON.stringify(params, null, 2)}\n`], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `T13-${mixture ? 'nasa9-mixture' : 'constant-gamma'}.simulation.json`; anchor.click(); URL.revokeObjectURL(url) }

function ProbeVisual({ mixture }: { mixture: boolean }) {
  return <svg className="tutorial-aircraft" viewBox="0 0 760 360" role="img" aria-label="Cylindrical probe in a 1800 kelvin supersonic exhaust stream"><defs><linearGradient id="t13-hot" x1="0" x2="1"><stop stopColor="#f8d794"/><stop offset="1" stopColor="#e7763c"/></linearGradient></defs><rect x="42" y="43" width="676" height="270" rx="24" fill="url(#t13-hot)" opacity=".34"/><path d="M90 180 H305" stroke="#d65f35" strokeWidth="8"/><path d="M287 162 L318 180 L287 198" fill="none" stroke="#d65f35" strokeWidth="8"/><text x="90" y="150">1800 K · 900 m/s</text><ellipse cx="430" cy="180" rx="30" ry="96" fill="#667068"/><path d="M374 78 Q315 180 374 282" fill="none" stroke={mixture ? '#9f3824' : '#c26b33'} strokeWidth={mixture ? 8 : 5}/><text x="505" y="120">50 mm probe</text><text x="505" y="180">{mixture ? 'M = 1.098' : 'M = 1.058'}</text><text x="505" y="215">{mixture ? 'γ = 1.300' : 'γ = 1.400'}</text><text x="505" y="250">600 K wall</text></svg>
}

export default function T13TutorialPage() {
  const [status, setStatus] = useState<Flow360Status | null>(null); const [stepIndex, setStepIndex] = useState(0); const [completed, setCompleted] = useState<string[]>(readProgress); const [mixture, setMixture] = useState(false); const [checksVisible, setChecksVisible] = useState(false); const [reviewed, setReviewed] = useState<string[]>([])
  const params = useMemo(() => t13Params(mixture), [mixture]); const checks = useMemo(() => validateT13Setup(params), [params]); const step = t13Steps[stepIndex]
  useEffect(() => { api.flow360Status().then(setStatus).catch(() => setStatus({ available: false })) }, []); useEffect(() => window.localStorage.setItem(storageKey, JSON.stringify(completed)), [completed])
  const finishStep = () => { setCompleted((current) => current.includes(step.id) ? current : [...current, step.id]); setStepIndex((current) => Math.min(current + 1, t13Steps.length - 1)) }
  const lesson = () => {
    switch (step.id) {
      case 'question': return <><div className="lesson-kicker"><Sparkles size={15}/> Engineering decision</div><h1>Is constant-gamma air accurate enough for a probe in 1800 K exhaust?</h1><p className="lesson-lead">A 50 mm cylindrical probe sees a 900 m/s turbine-exhaust stream while its wall is held at 600 K. The gas model affects sound speed, Mach number, shock compression, pressure loading, and the thermal state driving wall heat flux.</p><div className="lesson-decision-card"><span>DECISION</span><strong>Does temperature-dependent heat capacity materially alter the predicted aerothermal environment?</strong><p>Build a controlled comparison: retain the same state, velocity, viscosity, Geometry, mesh, boundaries, and numerics; replace only the constant-gamma species definition with frozen N2-O2 NASA-9 data.</p></div><div className="aircraft-stage"><ProbeVisual mixture={mixture}/></div><TutorialConceptBridge cfd={t13Pedagogy.cfdConcepts} flow360={t13Pedagogy.flow360Concepts}/></>
      case 'physics': return <><div className="lesson-kicker"><Thermometer size={15}/> Thermodynamic model</div><h1>Temperature-dependent properties and species transport are different capabilities.</h1><p className="lesson-lead">ThermallyPerfectGas evaluates heat capacity from the configured species polynomials. FrozenSpecies means the N2 and O2 fractions are fixed material inputs everywhere; this setup does not solve species conservation equations or chemistry.</p><div className="parameter-learning-grid">{t13ParameterCards.map((item) => <article key={item.label}><div><span className={`provenance ${item.provenance}`}>{item.provenance}</span><strong>{item.label}</strong></div><b>{item.value}</b><p>{item.why}</p></article>)}</div><div className="lesson-callout warning"><AlertTriangle size={17}/><p><strong>Flow360 25.10 capability boundary</strong>The pinned schema supports FrozenSpecies and NASA-9 thermodynamics but does not expose SpeciesTransportModel. Concentration fields, mixing, dissociation, combustion, and emissions are outside these Drafts.</p></div><button className="lesson-validate-button" onClick={() => setChecksVisible(true)}><ShieldCheck size={16}/> Validate the gas setup in the browser</button>{checksVisible && <div className="setup-checks">{checks.map((check) => <div className={check.passed ? 'passed' : 'failed'} key={check.id}>{check.passed ? <CheckCircle2 size={17}/> : <AlertTriangle size={17}/>}<span><strong>{check.label}</strong><small>{check.detail}</small></span></div>)}</div>}</>
      case 'scales': return <><div className="lesson-kicker"><Gauge size={15}/> Pre-solve scale analysis</div><h1>The gas model changes Mach even when velocity is unchanged.</h1><p className="lesson-lead">At 1800 K the frozen-mixture NASA-9 heat capacities give a lower gamma than the baseline. Sound speed falls by about 3.6%, so the 900 m/s stream moves farther above Mach one.</p><TutorialDerivations items={t13Pedagogy.derivations}/><div className="geometry-assumptions"><div><span>CONSTANT γ</span><strong>M 1.058</strong><small>a = 850.5 m/s</small></div><div><span>NASA-9 MIXTURE</span><strong>M 1.098</strong><small>a = 819.7 m/s</small></div><div><span>FLOW SCALE</span><strong>Re 1.51 × 10⁵</strong><small>q = 79.4 kPa</small></div></div></>
      case 'experiment': return <><div className="lesson-kicker"><GitCompare size={15}/> Controlled material experiment</div><h1>Replace only the caloric thermodynamics.</h1><p className="lesson-lead">The baseline represents γ = 1.4 with one constant-cp Air polynomial. The variant uses fixed N2 and O2 fractions with two NASA-9 temperature ranges per species. Both retain the identical Sutherland law.</p><TutorialPrediction experiment={t13Pedagogy.experiments[0]}/><div className="alpha-experiment"><div className="alpha-control" role="group" aria-label="Gas thermodynamic model"><button className={!mixture ? 'active' : ''} onClick={() => setMixture(false)}><span>Baseline</span><strong>Constant γ</strong></button><button className={mixture ? 'active' : ''} onClick={() => setMixture(true)}><span>Variant</span><strong>Frozen NASA-9</strong></button></div><div className="alpha-visual">{mixture ? <Flame size={82} strokeWidth={1.1}/> : <Thermometer size={82} strokeWidth={1.1}/>}<span>{mixture ? 'N2 0.767 · O2 0.233' : 'Air · cp/R = 3.5'}</span></div><div className="semantic-diff"><p className="eyebrow">MATERIAL DIFF</p><div><code>thermally_perfect_gas.species</code><span>Air</span><ArrowRight size={14}/><strong>{mixture ? 'N2 + O2' : 'Air'}</strong></div><small>{mixture ? 'NASA-9 temperature dependence is active.' : 'The constant-gamma baseline remains selected.'}</small></div></div><TutorialFailureModes items={t13Pedagogy.failureModes}/><button className="lesson-secondary-button" onClick={() => downloadJSON(params, mixture)}><Download size={15}/> Download selected setup</button></>
      case 'evidence': return <><div className="lesson-kicker"><ShieldCheck size={15}/> Aerothermal evidence</div><h1>Trace the material change from properties to engineering observables.</h1><p className="lesson-lead">First verify the coefficient ranges, composition, gamma, and sound speed. Then compare shock position and strength, surface pressure and heat flux, and finally mesh and convergence quality. That sequence makes the attribution testable.</p><div className="evidence-checklist">{t13Evidence.map((item) => { const selected = reviewed.includes(item.title); return <button className={selected ? 'reviewed' : ''} key={item.title} onClick={() => setReviewed((current) => selected ? current.filter((value) => value !== item.title) : [...current, item.title])}><span className="evidence-check">{selected && <Check size={15}/>}</span><span><strong>{item.title}</strong><small>{item.detail}</small></span></button> })}</div><div className={`lesson-callout ${reviewed.length === t13Evidence.length ? 'success' : ''}`}>{reviewed.length === t13Evidence.length ? <CheckCircle2 size={17}/> : <AlertTriangle size={17}/>}<p><strong>{reviewed.length}/5 reviewed</strong>{reviewed.length === t13Evidence.length ? 'The frozen-gas aerothermal evidence contract is complete.' : 'Review every requirement before creating the environment.'}</p></div><TutorialEvidenceRubric items={t13Pedagogy.evidenceRubric}/></>
      default: return <><div className="lesson-kicker"><Cloud size={15}/> Create the high-temperature gas environment</div><h1>Create both configured Case Drafts from the supplied probe.</h1><p className="lesson-lead">The app uploads the cylindrical-probe Geometry, creates one Project, registers the center Slice, and synchronizes constant-gamma and frozen NASA-9 Case Drafts with complete mesh, boundaries, material, solver, and evidence outputs.</p><div className="run-readiness-card"><div className="run-ready-icon"><CheckCircle2 size={30}/></div><div><span>CONFIGURATION STATUS</span><strong>Both high-temperature gas setups validated</strong><p>No mesh or solver Case is submitted; compute remains under your control in the Project workspace.</p></div></div><TutorialTransferCheck items={t13Pedagogy.transferQuestions}/><TutorialEnvironmentBuilder status={status} tutorialId="T13" defaultProjectName="Tutorial T13 · hot exhaust probe" heading="Build the T13 thermodynamic-model comparison" description="The app uploads the bundled probe and creates constant-gamma and frozen N2-O2 NASA-9 Case Drafts." configurationSummary="1800 K and 900 m/s reference state, Sutherland viscosity, AutomatedFarfield, 600 K probe Wall, center Slice, aerothermal outputs" draftKind="Case" baselineValue="Constant-gamma hot air" variantValue="Frozen N2-O2 NASA-9 mixture" successDescription="Both Case Draft parameter sets are synced. No surface mesh, volume mesh, or solver Case has been submitted." createEnvironment={createT13Environment}/></>
    }
  }
  return <div className="tutorial-player-page"><TopBar status={status} title="Guided tutorial · T13"/><aside className="tutorial-outline"><Link className="tutorial-back" to="/tutorials"><ArrowLeft size={14}/> All tutorials</Link><div className="tutorial-outline-title"><span>T13</span><h2>Thermally perfect gas</h2><small>High-temperature CFD · 20–25 min</small></div><div className="tutorial-progress"><div><span>Progress</span><strong>{t13Progress(completed)}%</strong></div><progress value={t13Progress(completed)} max="100"/></div><nav aria-label="Tutorial steps">{t13Steps.map((item, index) => <button key={item.id} className={`${index === stepIndex ? 'active' : ''} ${completed.includes(item.id) ? 'complete' : ''}`} onClick={() => setStepIndex(index)}><span>{completed.includes(item.id) ? <Check size={13}/> : item.label}</span><div><strong>{item.title}</strong><small>{item.summary}</small></div></button>)}</nav><button className="tutorial-reset" onClick={() => { setCompleted([]); setStepIndex(0); setReviewed([]); setChecksVisible(false); setMixture(false) }}><RotateCcw size={13}/> Reset progress</button></aside><main className="tutorial-lesson"><div className="lesson-content">{lesson()}</div><footer className="lesson-footer"><button className="lesson-previous" disabled={stepIndex === 0} onClick={() => setStepIndex((current) => Math.max(0, current - 1))}><ArrowLeft size={15}/> Previous</button><span>Step {stepIndex + 1} of {t13Steps.length}</span>{stepIndex < t13Steps.length - 1 ? <button className="lesson-next" onClick={finishStep}>Complete & continue <ArrowRight size={15}/></button> : <button className="lesson-next" onClick={() => setCompleted((current) => current.includes(step.id) ? current : [...current, step.id])}><Check size={15}/> Mark tutorial complete</button>}</footer></main></div>
}
