import { AlertTriangle, ArrowLeft, ArrowRight, Check, CheckCircle2, Cloud, Download, Gauge, GitCompare, RotateCcw, ShieldCheck, Sparkles, Waves, Wind } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import type { Flow360Status } from '../api/client'
import { api } from '../api/client'
import TopBar from '../components/TopBar'
import TutorialEnvironmentBuilder from '../components/TutorialEnvironmentBuilder'
import { TutorialConceptBridge, TutorialDerivations, TutorialEvidenceRubric, TutorialFailureModes, TutorialPrediction, TutorialTransferCheck } from '../components/TutorialTeachingBlocks'
import { createT14Environment, t14Evidence, t14ParameterCards, t14Params, t14Pedagogy, t14Progress, t14Steps, validateT14Setup } from '../tutorials/t14'

const storageKey = 'vibesim.tutorial.T14.completed'
function readProgress() { try { const parsed = JSON.parse(window.localStorage.getItem(storageKey) || '[]'); return Array.isArray(parsed) ? parsed.filter((item): item is string => typeof item === 'string') : [] } catch { return [] } }
function downloadJSON(params: Record<string, unknown>, sst: boolean) { const blob = new Blob([`${JSON.stringify(params, null, 2)}\n`], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `T14-${sst ? 'k-omega-sst' : 'spalart-allmaras'}.simulation.json`; anchor.click(); URL.revokeObjectURL(url) }
function WakeVisual({ sst }: { sst: boolean }) { return <svg className="tutorial-aircraft" viewBox="0 0 760 360" role="img" aria-label="Rear-step bluff body and separated wake"><defs><linearGradient id="t14-wake" x1="0" x2="1"><stop stopColor="#dce9d0"/><stop offset="1" stopColor="#b7ced8"/></linearGradient></defs><rect x="38" y="38" width="684" height="280" rx="24" fill="url(#t14-wake)" opacity=".48"/><path d="M82 180 H245" stroke="#397991" strokeWidth="8"/><path d="M227 162 L258 180 L227 198" fill="none" stroke="#397991" strokeWidth="8"/><path d="M285 235 V145 H345 V95 H475 V235 Z" fill="#687268"/><path d={sst ? 'M475 105 C535 85 625 120 666 176 C610 150 553 156 475 218' : 'M475 105 C535 98 590 132 650 180 C590 162 530 172 475 218'} fill="none" stroke={sst ? '#9b5335' : '#708c3c'} strokeWidth="7" strokeDasharray="12 9"/><text x="80" y="150">30 m/s</text><text x="300" y="272">1.2 m body</text><text x="525" y="270">separated wake</text><text x="520" y="75">{sst ? 'k-ω SST' : 'Spalart–Allmaras'}</text></svg> }

export default function T14TutorialPage() {
  const [status, setStatus] = useState<Flow360Status | null>(null); const [stepIndex, setStepIndex] = useState(0); const [completed, setCompleted] = useState<string[]>(readProgress); const [sst, setSst] = useState(false); const [checksVisible, setChecksVisible] = useState(false); const [reviewed, setReviewed] = useState<string[]>([])
  const params = useMemo(() => t14Params(sst), [sst]); const checks = useMemo(() => validateT14Setup(params), [params]); const step = t14Steps[stepIndex]
  useEffect(() => { api.flow360Status().then(setStatus).catch(() => setStatus({ available: false })) }, []); useEffect(() => window.localStorage.setItem(storageKey, JSON.stringify(completed)), [completed])
  const finishStep = () => { setCompleted((current) => current.includes(step.id) ? current : [...current, step.id]); setStepIndex((current) => Math.min(current + 1, t14Steps.length - 1)) }
  const lesson = () => {
    switch (step.id) {
      case 'question': return <><div className="lesson-kicker"><Sparkles size={15}/> Engineering decision</div><h1>How sensitive is rear-step pressure drag to the RANS closure?</h1><p className="lesson-lead">A 1.2 m high bluff body sits in a 30 m/s low-turbulence wind tunnel. Its roof step forces separation, and the modeled shear-layer growth affects reattachment, base pressure, wake recovery, and drag.</p><div className="lesson-decision-card"><span>DECISION</span><strong>Can either closure support the design load?</strong><p>Compare Spalart–Allmaras and k-omega SST under one shared experiment, then require mesh, convergence, and external reference evidence before selecting a model.</p></div><div className="aircraft-stage"><WakeVisual sst={sst}/></div><TutorialConceptBridge cfd={t14Pedagogy.cfdConcepts} flow360={t14Pedagogy.flow360Concepts}/></>
      case 'closure': return <><div className="lesson-kicker"><Waves size={15}/> Closure and boundary quantities</div><h1>RANS models turbulent transport; it does not resolve the wake eddies.</h1><p className="lesson-lead">SA transports one modified-viscosity working variable and is often economical for wall-bounded aerodynamic flow. SST transports k and omega and blends near-wall and outer-flow behaviour, often changing adverse-pressure-gradient separation.</p><div className="parameter-learning-grid">{t14ParameterCards.map((item) => <article key={item.label}><div><span className={`provenance ${item.provenance}`}>{item.provenance}</span><strong>{item.label}</strong></div><b>{item.value}</b><p>{item.why}</p></article>)}</div><div className="lesson-callout warning"><AlertTriangle size={17}/><p><strong>Steady-RANS boundary</strong>If residuals and CD remain periodic, do not force a steady verdict. The wake may require an unsteady method, time-step sensitivity, and a statistically converged averaging window.</p></div><button className="lesson-validate-button" onClick={() => setChecksVisible(true)}><ShieldCheck size={16}/> Validate the selected RANS setup</button>{checksVisible && <div className="setup-checks">{checks.map((check) => <div className={check.passed ? 'passed' : 'failed'} key={check.id}>{check.passed ? <CheckCircle2 size={17}/> : <AlertTriangle size={17}/>}<span><strong>{check.label}</strong><small>{check.detail}</small></span></div>)}</div>}</>
      case 'scales': return <><div className="lesson-kicker"><Gauge size={15}/> Pre-solve scale analysis</div><h1>Translate facility turbulence data into closure inputs.</h1><p className="lesson-lead">The 0.5% intensity and 10 mm length scale imply an SST kinetic-energy scale of 0.03375 m²/s² and an explanatory omega scale near 33.5 s⁻¹. These values require facility-specific justification in production work.</p><TutorialDerivations items={t14Pedagogy.derivations}/><div className="geometry-assumptions"><div><span>REYNOLDS NUMBER</span><strong>2.46 × 10⁶</strong><small>ρUH/μ</small></div><div><span>DYNAMIC PRESSURE</span><strong>551.25 Pa</strong><small>½ρU²</small></div><div><span>SST INPUT SCALE</span><strong>k = 0.03375</strong><small>ω ≈ 33.5 s⁻¹</small></div></div></>
      case 'experiment': return <><div className="lesson-kicker"><GitCompare size={15}/> Controlled closure experiment</div><h1>Change the closure and the quantities that initialize it.</h1><p className="lesson-lead">The SA Draft declares modified turbulent viscosity ratio 70. The SST Draft declares intensity 0.005 and length scale 0.01 m. Geometry, state, mesh, references, wall, steps, and evidence outputs remain identical.</p><TutorialPrediction experiment={t14Pedagogy.experiments[0]}/><div className="alpha-experiment"><div className="alpha-control" role="group" aria-label="RANS turbulence closure"><button className={!sst ? 'active' : ''} onClick={() => setSst(false)}><span>Baseline</span><strong>Spalart–Allmaras</strong></button><button className={sst ? 'active' : ''} onClick={() => setSst(true)}><span>Variant</span><strong>k-omega SST</strong></button></div><div className="alpha-visual">{sst ? <Waves size={82} strokeWidth={1.1}/> : <Wind size={82} strokeWidth={1.1}/>}<span>{sst ? 'I = 0.5% · L = 0.01 m' : 'modified viscosity ratio = 70'}</span></div><div className="semantic-diff"><p className="eyebrow">CLOSURE DIFF</p><div><code>Fluid.turbulence_model_solver</code><span>SA</span><ArrowRight size={14}/><strong>{sst ? 'kOmegaSST' : 'SA'}</strong></div><small>{sst ? 'SST and its compatible freestream quantities are active.' : 'The SA baseline remains selected.'}</small></div></div><TutorialFailureModes items={t14Pedagogy.failureModes}/><button className="lesson-secondary-button" onClick={() => downloadJSON(params, sst)}><Download size={15}/> Download selected setup</button></>
      case 'evidence': return <><div className="lesson-kicker"><ShieldCheck size={15}/> Model-form evidence</div><h1>A turbulence-model comparison needs signed fields and reference data.</h1><p className="lesson-lead">Use zero Cf and negative streamwise velocity to locate separation and reattachment. Connect those observations to base pressure and CD, then separate model effects from wall treatment, mesh error, and incomplete convergence.</p><div className="evidence-checklist">{t14Evidence.map((item) => { const selected = reviewed.includes(item.title); return <button className={selected ? 'reviewed' : ''} key={item.title} onClick={() => setReviewed((current) => selected ? current.filter((value) => value !== item.title) : [...current, item.title])}><span className="evidence-check">{selected && <Check size={15}/>}</span><span><strong>{item.title}</strong><small>{item.detail}</small></span></button> })}</div><div className={`lesson-callout ${reviewed.length === t14Evidence.length ? 'success' : ''}`}>{reviewed.length === t14Evidence.length ? <CheckCircle2 size={17}/> : <AlertTriangle size={17}/>}<p><strong>{reviewed.length}/5 reviewed</strong>{reviewed.length === t14Evidence.length ? 'The RANS model-sensitivity evidence contract is complete.' : 'Review every requirement before creating the environment.'}</p></div><TutorialEvidenceRubric items={t14Pedagogy.evidenceRubric}/></>
      default: return <><div className="lesson-kicker"><Cloud size={15}/> Create the RANS comparison environment</div><h1>Create both configured Case Drafts from the supplied rear-step body.</h1><p className="lesson-lead">The app uploads the analytic Geometry, creates one Project, registers the wake Box and center Slice, and synchronizes complete SA and SST Case Drafts.</p><div className="run-readiness-card"><div className="run-ready-icon"><CheckCircle2 size={30}/></div><div><span>CONFIGURATION STATUS</span><strong>Both RANS setups validated</strong><p>No mesh or solver Case is submitted; compute remains under your control in the Project workspace.</p></div></div><TutorialTransferCheck items={t14Pedagogy.transferQuestions}/><TutorialEnvironmentBuilder status={status} tutorialId="T14" defaultProjectName="Tutorial T14 · rear-step RANS comparison" heading="Build the T14 turbulence-model comparison" description="The app uploads the bundled rear-step body and creates Spalart-Allmaras and k-omega SST Case Drafts." configurationSummary="30 m/s air, shared wall and wake mesh, SA or SST closure, compatible freestream turbulence quantities, separation and drag outputs" draftKind="Case" baselineValue="Spalart-Allmaras rear-step wake" variantValue="k-omega SST rear-step wake" successDescription="Both Case Draft parameter sets are synced. No surface mesh, volume mesh, or solver Case has been submitted." createEnvironment={createT14Environment}/></>
    }
  }
  return <div className="tutorial-player-page"><TopBar status={status} title="Guided tutorial · T14"/><aside className="tutorial-outline"><Link className="tutorial-back" to="/tutorials"><ArrowLeft size={14}/> All tutorials</Link><div className="tutorial-outline-title"><span>T14</span><h2>RANS model sensitivity</h2><small>Turbulence modelling · 20–25 min</small></div><div className="tutorial-progress"><div><span>Progress</span><strong>{t14Progress(completed)}%</strong></div><progress value={t14Progress(completed)} max="100"/></div><nav aria-label="Tutorial steps">{t14Steps.map((item, index) => <button key={item.id} className={`${index === stepIndex ? 'active' : ''} ${completed.includes(item.id) ? 'complete' : ''}`} onClick={() => setStepIndex(index)}><span>{completed.includes(item.id) ? <Check size={13}/> : item.label}</span><div><strong>{item.title}</strong><small>{item.summary}</small></div></button>)}</nav><button className="tutorial-reset" onClick={() => { setCompleted([]); setStepIndex(0); setReviewed([]); setChecksVisible(false); setSst(false) }}><RotateCcw size={13}/> Reset progress</button></aside><main className="tutorial-lesson"><div className="lesson-content">{lesson()}</div><footer className="lesson-footer"><button className="lesson-previous" disabled={stepIndex === 0} onClick={() => setStepIndex((current) => Math.max(0, current - 1))}><ArrowLeft size={15}/> Previous</button><span>Step {stepIndex + 1} of {t14Steps.length}</span>{stepIndex < t14Steps.length - 1 ? <button className="lesson-next" onClick={finishStep}>Complete & continue <ArrowRight size={15}/></button> : <button className="lesson-next" onClick={() => setCompleted((current) => current.includes(step.id) ? current : [...current, step.id])}><Check size={15}/> Mark tutorial complete</button>}</footer></main></div>
}
