import { AlertTriangle, ArrowLeft, ArrowRight, Check, CheckCircle2, Cloud, Download, Gauge, GitBranch, RotateCcw, ShieldCheck, Sparkles, TimerReset, Waves } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import type { Flow360Status } from '../api/client'
import { api } from '../api/client'
import TopBar from '../components/TopBar'
import TutorialEnvironmentBuilder from '../components/TutorialEnvironmentBuilder'
import { TutorialConceptBridge, TutorialDerivations, TutorialEvidenceRubric, TutorialFailureModes, TutorialPrediction, TutorialTransferCheck } from '../components/TutorialTeachingBlocks'
import { createT15Environment, t15Evidence, t15ParameterCards, t15Params, t15Pedagogy, t15Progress, t15Steps, validateT15Setup, type T15Mode } from '../tutorials/t15'

const storageKey = 'vibesim.tutorial.T15.completed'
function readProgress() { try { const parsed = JSON.parse(window.localStorage.getItem(storageKey) || '[]'); return Array.isArray(parsed) ? parsed.filter((item): item is string => typeof item === 'string') : [] } catch { return [] } }
function modeLabel(mode: T15Mode) { return mode === 'rans' ? 'fully turbulent SST' : mode === 'transition' ? 'SST + AFT transition' : 'unsteady SST-DDES' }
function downloadJSON(params: Record<string, unknown>, mode: T15Mode) { const blob = new Blob([`${JSON.stringify(params, null, 2)}\n`], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `T15-${mode}.simulation.json`; anchor.click(); URL.revokeObjectURL(url) }
function HighLiftVisual({ mode }: { mode: T15Mode }) { const color = mode === 'rans' ? '#708c3c' : mode === 'transition' ? '#397991' : '#9b5335'; return <svg className="tutorial-aircraft" viewBox="0 0 760 360" role="img" aria-label="Finite-span three-element wing near stall"><rect x="35" y="35" width="690" height="290" rx="24" fill="#e6eee4"/><path d="M70 178 H215" stroke="#397991" strokeWidth="8"/><path d="M198 160 L228 178 L198 196" fill="none" stroke="#397991" strokeWidth="8"/><path d="M265 150 Q345 112 485 155 Q370 181 265 178 Z" fill="#687268"/><path d="M222 164 Q246 138 270 157 Q248 180 222 181 Z" fill="#7b857b"/><path d="M478 170 L602 220 L585 238 L470 190 Z" fill="#7b857b"/><path d={mode === 'ddes' ? 'M420 145 C485 95 560 105 620 150 C560 125 510 185 665 215 C575 200 530 265 440 185' : 'M420 145 C505 125 570 155 650 205'} fill="none" stroke={color} strokeWidth="7" strokeDasharray={mode === 'ddes' ? '8 7' : '14 10'}/><text x="70" y="145">50 m/s · 16°</text><text x="290" y="270">slat · main wing · flap</text><text x="480" y="85">{modeLabel(mode)}</text></svg> }

export default function T15TutorialPage() {
  const [status, setStatus] = useState<Flow360Status | null>(null); const [stepIndex, setStepIndex] = useState(0); const [completed, setCompleted] = useState<string[]>(readProgress); const [mode, setMode] = useState<T15Mode>('rans'); const [checksVisible, setChecksVisible] = useState(false); const [reviewed, setReviewed] = useState<string[]>([])
  const params = useMemo(() => t15Params(mode), [mode]); const checks = useMemo(() => validateT15Setup(params), [params]); const step = t15Steps[stepIndex]
  useEffect(() => { api.flow360Status().then(setStatus).catch(() => setStatus({ available: false })) }, []); useEffect(() => window.localStorage.setItem(storageKey, JSON.stringify(completed)), [completed])
  const finishStep = () => { setCompleted((current) => current.includes(step.id) ? current : [...current, step.id]); setStepIndex((current) => Math.min(current + 1, t15Steps.length - 1)) }
  const lesson = () => {
    switch (step.id) {
      case 'question': return <><div className="lesson-kicker"><Sparkles size={15}/> Engineering diagnosis</div><h1>Does the high-lift decision need transition modelling, resolved unsteadiness, or neither?</h1><p className="lesson-lead">A finite-span three-element wing operates at 50 m/s and 16° in a low-turbulence tunnel. Fully turbulent SST supplies the reference mean-load model; the other branches are justified only by a specific missing-physics hypothesis.</p><div className="lesson-decision-card"><span>DECISION</span><strong>Which method can support the near-stall load assessment?</strong><p>Use transition modelling for uncertain laminar-to-turbulent onset. Use DDES for time-dependent separated structures only after its grid and sampling requirements are affordable and testable.</p></div><div className="aircraft-stage"><HighLiftVisual mode={mode}/></div><TutorialConceptBridge cfd={t15Pedagogy.cfdConcepts} flow360={t15Pedagogy.flow360Concepts}/></>
      case 'models': return <><div className="lesson-kicker"><GitBranch size={15}/> Model ownership and prerequisites</div><h1>AFT and DDES attach to different places and require different evidence.</h1><p className="lesson-lead">Flow360 stores AmplificationFactorTransport beside the SST turbulence solver. DetachedEddySimulation lives inside the SST hybrid-model field. Neither setting repairs an unsuitable mesh or an unsupported physical hypothesis.</p><div className="parameter-learning-grid">{t15ParameterCards.map((item) => <article key={item.label}><div><span className={`provenance ${item.provenance}`}>{item.provenance}</span><strong>{item.label}</strong></div><b>{item.value}</b><p>{item.why}</p></article>)}</div><div className="lesson-callout warning"><AlertTriangle size={17}/><p><strong>Method boundary</strong>The transition branch remains steady RANS and predicts onset. The DDES branch becomes unsteady and requires statistically converged samples; their costs and conclusions cannot be compared as one scalar fidelity level.</p></div><button className="lesson-validate-button" onClick={() => setChecksVisible(true)}><ShieldCheck size={16}/> Validate the selected model branch</button>{checksVisible && <div className="setup-checks">{checks.map((check) => <div className={check.passed ? 'passed' : 'failed'} key={check.id}>{check.passed ? <CheckCircle2 size={17}/> : <AlertTriangle size={17}/>}<span><strong>{check.label}</strong><small>{check.detail}</small></span></div>)}</div>}</>
      case 'scales': return <><div className="lesson-kicker"><Gauge size={15}/> Pre-solve scale analysis</div><h1>Express transition and DDES inputs in physical scales.</h1><p className="lesson-lead">The chord Reynolds number is about 3.42 million. One convective time is 0.020 s; the tutorial DDES step is 0.01 convective time and the 5000-step budget spans 50 convective times before sensitivity evidence.</p><TutorialDerivations items={t15Pedagogy.derivations}/><div className="geometry-assumptions"><div><span>REYNOLDS NUMBER</span><strong>3.42 × 10⁶</strong><small>ρUc/μ</small></div><div><span>TRANSITION INPUT</span><strong>Ncrit ≈ 8.15</strong><small>from Tu = 0.10%</small></div><div><span>DDES TIME SCALE</span><strong>Δt/tc = 0.01</strong><small>50 tc total budget</small></div></div></>
      case 'branches': return <><div className="lesson-kicker"><Waves size={15}/> Three model branches</div><h1>Choose a branch from the missing physics, not from its name.</h1><p className="lesson-lead">The transition branch adds AFT and solutionTransition while staying steady. The DDES branch adds DDES shielding and changes time advancement to 5000 physical steps at 0.0002 s.</p><TutorialPrediction experiment={t15Pedagogy.experiments[0]}/><TutorialPrediction experiment={t15Pedagogy.experiments[1]}/><div className="alpha-experiment"><div className="alpha-control" role="group" aria-label="High-lift model branch"><button className={mode === 'rans' ? 'active' : ''} onClick={() => setMode('rans')}><span>Reference</span><strong>Fully turbulent SST</strong></button><button className={mode === 'transition' ? 'active' : ''} onClick={() => setMode('transition')}><span>Onset branch</span><strong>SST + AFT transition</strong></button><button className={mode === 'ddes' ? 'active' : ''} onClick={() => setMode('ddes')}><span>Unsteady branch</span><strong>SST-DDES</strong></button></div><div className="alpha-visual"><TimerReset size={82} strokeWidth={1.1}/><span>{mode === 'rans' ? 'steady · transition disabled' : mode === 'transition' ? 'steady · Ncrit ≈ 8.15' : 'unsteady · Δt = 0.0002 s'}</span></div><div className="semantic-diff"><p className="eyebrow">METHOD DIFF</p><div><code>{mode === 'transition' ? 'Fluid.transition_model_solver' : mode === 'ddes' ? 'kOmegaSST.hybrid_model + time_stepping' : 'reference configuration'}</code><span>SST</span><ArrowRight size={14}/><strong>{modeLabel(mode)}</strong></div><small>{mode === 'rans' ? 'The mean-load reference remains selected.' : mode === 'transition' ? 'AFT onset transport and its output are active.' : 'DDES and the unsteady sampling budget are active.'}</small></div></div><button className="lesson-secondary-button" onClick={() => downloadJSON(params, mode)}><Download size={15}/> Download selected setup</button></>
      case 'evidence': return <><div className="lesson-kicker"><ShieldCheck size={15}/> Branch-specific acceptance gates</div><h1>Transition needs onset evidence; DDES needs grid, time, and statistics evidence.</h1><p className="lesson-lead">Keep common observables traceable, then apply the additional gate belonging to the chosen physics. External reference data remains necessary for any design conclusion.</p><div className="evidence-checklist">{t15Evidence.map((item) => { const selected = reviewed.includes(item.title); return <button className={selected ? 'reviewed' : ''} key={item.title} onClick={() => setReviewed((current) => selected ? current.filter((value) => value !== item.title) : [...current, item.title])}><span className="evidence-check">{selected && <Check size={15}/>}</span><span><strong>{item.title}</strong><small>{item.detail}</small></span></button> })}</div><div className={`lesson-callout ${reviewed.length === t15Evidence.length ? 'success' : ''}`}>{reviewed.length === t15Evidence.length ? <CheckCircle2 size={17}/> : <AlertTriangle size={17}/>}<p><strong>{reviewed.length}/6 reviewed</strong>{reviewed.length === t15Evidence.length ? 'The model-upgrade evidence contract is complete.' : 'Review every gate before creating the comparison environment.'}</p></div><TutorialFailureModes items={t15Pedagogy.failureModes}/><TutorialEvidenceRubric items={t15Pedagogy.evidenceRubric}/></>
      default: return <><div className="lesson-kicker"><Cloud size={15}/> Create the model-upgrade environment</div><h1>Create three configured Case Drafts from the supplied high-lift wing.</h1><p className="lesson-lead">The app uploads the finite-span three-element Geometry, registers the midspan Slice and separated-flow Box, and synchronizes the fully turbulent, transition, and DDES parameter sets.</p><div className="run-readiness-card"><div className="run-ready-icon"><CheckCircle2 size={30}/></div><div><span>CONFIGURATION STATUS</span><strong>All three model branches validated</strong><p>No surface mesh, volume mesh, or solver Case is submitted. Each Draft remains under your control in the Project workspace.</p></div></div><TutorialTransferCheck items={t15Pedagogy.transferQuestions}/><TutorialEnvironmentBuilder status={status} tutorialId="T15" defaultProjectName="Tutorial T15 · high-lift model upgrade" heading="Build the T15 transition and DDES environment" description="The app uploads the bundled high-lift wing and creates fully turbulent SST, AFT transition, and unsteady SST-DDES Case Drafts." configurationSummary="50 m/s at 16°, common wall-resolved mesh and outputs, AFT onset branch, DDES unsteady branch" draftKind="Case" draftCount={3} baselineValue="Fully turbulent SST" variantValue="SST + AFT transition" thirdValue="Unsteady SST-DDES" successDescription="All three Case Draft parameter sets are synced. No surface mesh, volume mesh, or solver Case has been submitted." createEnvironment={createT15Environment}/></>
    }
  }
  return <div className="tutorial-player-page"><TopBar status={status} title="Guided tutorial · T15"/><aside className="tutorial-outline"><Link className="tutorial-back" to="/tutorials"><ArrowLeft size={14}/> All tutorials</Link><div className="tutorial-outline-title"><span>T15</span><h2>Transition or DDES?</h2><small>Model upgrade · 25–30 min</small></div><div className="tutorial-progress"><div><span>Progress</span><strong>{t15Progress(completed)}%</strong></div><progress value={t15Progress(completed)} max="100"/></div><nav aria-label="Tutorial steps">{t15Steps.map((item, index) => <button key={item.id} className={`${index === stepIndex ? 'active' : ''} ${completed.includes(item.id) ? 'complete' : ''}`} onClick={() => setStepIndex(index)}><span>{completed.includes(item.id) ? <Check size={13}/> : item.label}</span><div><strong>{item.title}</strong><small>{item.summary}</small></div></button>)}</nav><button className="tutorial-reset" onClick={() => { setCompleted([]); setStepIndex(0); setReviewed([]); setChecksVisible(false); setMode('rans') }}><RotateCcw size={13}/> Reset progress</button></aside><main className="tutorial-lesson"><div className="lesson-content">{lesson()}</div><footer className="lesson-footer"><button className="lesson-previous" disabled={stepIndex === 0} onClick={() => setStepIndex((current) => Math.max(0, current - 1))}><ArrowLeft size={15}/> Previous</button><span>Step {stepIndex + 1} of {t15Steps.length}</span>{stepIndex < t15Steps.length - 1 ? <button className="lesson-next" onClick={finishStep}>Complete & continue <ArrowRight size={15}/></button> : <button className="lesson-next" onClick={() => setCompleted((current) => current.includes(step.id) ? current : [...current, step.id])}><Check size={15}/> Mark tutorial complete</button>}</footer></main></div>
}
