import { Activity, AlertTriangle, ArrowLeft, ArrowRight, Check, CheckCircle2, Cloud, Download, Gauge, GitBranch, RotateCcw, ShieldCheck, Sparkles, Wrench } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import type { Flow360Status } from '../api/client'
import { api } from '../api/client'
import TopBar from '../components/TopBar'
import TutorialEnvironmentBuilder from '../components/TutorialEnvironmentBuilder'
import { TutorialConceptBridge, TutorialDerivations, TutorialEvidenceRubric, TutorialFailureModes, TutorialPrediction, TutorialTransferCheck } from '../components/TutorialTeachingBlocks'
import { createT16Environment, t16Evidence, t16ParameterCards, t16Params, t16Pedagogy, t16Progress, t16Steps, validateT16Setup, type T16Mode } from '../tutorials/t16'

const storageKey = 'vibesim.tutorial.T16.completed'
function readProgress() { try { const parsed = JSON.parse(window.localStorage.getItem(storageKey) || '[]'); return Array.isArray(parsed) ? parsed.filter((item): item is string => typeof item === 'string') : [] } catch { return [] } }
function modeLabel(mode: T16Mode) { return mode === 'recovery' ? 'conservative recovery' : mode === 'accuracy' ? 'restored second order' : 'steady Krylov + SLAU2' }
function downloadJSON(params: Record<string, unknown>, mode: T16Mode) { const blob = new Blob([`${JSON.stringify(params, null, 2)}\n`], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `T16-${mode}.simulation.json`; anchor.click(); URL.revokeObjectURL(url) }
function ResidualVisual({ mode }: { mode: T16Mode }) { const path = mode === 'recovery' ? 'M75 95 L135 135 L195 148 L255 165 L315 174 L375 185 L435 190 L495 198 L555 205 L635 211' : mode === 'accuracy' ? 'M75 95 L135 120 L195 112 L255 145 L315 153 L375 170 L435 179 L495 190 L555 198 L635 207' : 'M75 95 L135 132 L195 151 L255 168 L315 184 L375 196 L435 208 L495 216 L555 222 L635 228'; const color = mode === 'recovery' ? '#9b6b35' : mode === 'accuracy' ? '#397991' : '#708c3c'; return <svg className="tutorial-aircraft" viewBox="0 0 760 320" role="img" aria-label="Illustrative residual histories for the three numerical stages"><rect x="35" y="30" width="690" height="250" rx="24" fill="#e6eee4"/><path d="M70 65 V245 H680" fill="none" stroke="#879188" strokeWidth="2"/><path d={path} fill="none" stroke={color} strokeWidth="7"/><path d="M75 115 H650 M75 165 H650 M75 215 H650" stroke="#c4cec5" strokeWidth="1" strokeDasharray="6 7"/><text x="80" y="55">nonlinear residual · schematic</text><text x="485" y="260">pseudo-step</text><text x="470" y="82">{modeLabel(mode)}</text></svg> }

export default function T16TutorialPage() {
  const [status, setStatus] = useState<Flow360Status | null>(null); const [stepIndex, setStepIndex] = useState(0); const [completed, setCompleted] = useState<string[]>(readProgress); const [mode, setMode] = useState<T16Mode>('recovery'); const [checksVisible, setChecksVisible] = useState(false); const [reviewed, setReviewed] = useState<string[]>([])
  const params = useMemo(() => t16Params(mode), [mode]); const checks = useMemo(() => validateT16Setup(params), [params]); const step = t16Steps[stepIndex]
  useEffect(() => { api.flow360Status().then(setStatus).catch(() => setStatus({ available: false })) }, []); useEffect(() => window.localStorage.setItem(storageKey, JSON.stringify(completed)), [completed])
  const finishStep = () => { setCompleted((current) => current.includes(step.id) ? current : [...current, step.id]); setStepIndex((current) => Math.min(current + 1, t16Steps.length - 1)) }
  const lesson = () => {
    switch (step.id) {
      case 'symptom': return <><div className="lesson-kicker"><Sparkles size={15}/> Engineering diagnosis</div><h1>What failed first: the physical setup, nonlinear update, or linear solve?</h1><p className="lesson-lead">A finite-span loaded vane at Mach 0.30 and 12° develops a difficult steady history. Before changing a coefficient, classify whether the case diverges, stalls, oscillates, or converges to an answer that remains numerically untrustworthy.</p><div className="lesson-decision-card"><span>DECISION</span><strong>Which configuration can support the reported vane loads?</strong><p>The recovery Draft establishes bounded diagnostic behavior. The accuracy Draft restores second order for reported loads. The Krylov/SLAU2 Draft is accepted only when compatibility, convergence efficiency, and load agreement pass.</p></div><div className="aircraft-stage"><ResidualVisual mode={mode}/></div><TutorialConceptBridge cfd={t16Pedagogy.cfdConcepts} flow360={t16Pedagogy.flow360Concepts}/></>
      case 'evidence': return <><div className="lesson-kicker"><Activity size={15}/> Evidence before tuning</div><h1>Read six evidence channels as one timeline.</h1><p className="lesson-lead">Nonlinear residuals show between-step progress. Linear residuals show work inside each implicit solve. CFL and line search reveal accepted update size; force and state histories show whether numerical progress remains physically useful.</p><div className="parameter-learning-grid">{t16ParameterCards.map((item) => <article key={item.label}><div><span className={`provenance ${item.provenance}`}>{item.provenance}</span><strong>{item.label}</strong></div><b>{item.value}</b><p>{item.why}</p></article>)}</div><div className="lesson-callout warning"><AlertTriangle size={17}/><p><strong>Cause boundary</strong>A numerical control cannot repair a disconnected mesh, wrong boundary assignment, missing physics, or unresolved gradient. Use maximum-residual location and state bounds to return to the responsible model layer.</p></div><button className="lesson-validate-button" onClick={() => setChecksVisible(true)}><ShieldCheck size={16}/> Validate the selected numerical stage</button>{checksVisible && <div className="setup-checks">{checks.map((check) => <div className={check.passed ? 'passed' : 'failed'} key={check.id}>{check.passed ? <CheckCircle2 size={17}/> : <AlertTriangle size={17}/>}<span><strong>{check.label}</strong><small>{check.detail}</small></span></div>)}</div>}</>
      case 'controls': return <><div className="lesson-kicker"><Gauge size={15}/> Numerical controls and cost</div><h1>Change the control that owns the observed failure mechanism.</h1><p className="lesson-lead">Flux and reconstruction control face states. The linear solver controls each implicit system. Jacobian and equation frequencies control how often those systems are refreshed. Line search controls nonlinear step acceptance.</p><TutorialDerivations items={t16Pedagogy.derivations}/><div className="geometry-assumptions"><div><span>FLOW SCALE</span><strong>U ≈ 102.1 m/s</strong><small>M = 0.30 at 288.15 K</small></div><div><span>REYNOLDS NUMBER</span><strong>6.99 × 10⁶</strong><small>based on 1 m chord</small></div><div><span>KRYLOV CEILING</span><strong>375 sweeps</strong><small>15 × 25 per pseudo-step</small></div></div></>
      case 'ladder': return <><div className="lesson-kicker"><GitBranch size={15}/> Staged numerical ladder</div><h1>Recover bounded behavior, restore accuracy, then test efficiency.</h1><p className="lesson-lead">Do not interpret the three Drafts as equal alternatives. Stage 1 is diagnostic, Stage 2 is the reporting candidate, and Stage 3 is a separate steady efficiency experiment with explicit compatibility rules.</p><TutorialPrediction experiment={t16Pedagogy.experiments[0]}/><TutorialPrediction experiment={t16Pedagogy.experiments[1]}/><div className="alpha-experiment"><div className="alpha-control" role="group" aria-label="Numerical diagnosis stage"><button className={mode === 'recovery' ? 'active' : ''} onClick={() => setMode('recovery')}><span>Stage 1</span><strong>Conservative recovery</strong></button><button className={mode === 'accuracy' ? 'active' : ''} onClick={() => setMode('accuracy')}><span>Stage 2</span><strong>Restore second order</strong></button><button className={mode === 'krylov' ? 'active' : ''} onClick={() => setMode('krylov')}><span>Stage 3</span><strong>Krylov + SLAU2</strong></button></div><div className="alpha-visual"><Wrench size={82} strokeWidth={1.1}/><span>{mode === 'recovery' ? 'Roe · order 1 · CFL × 0.25' : mode === 'accuracy' ? 'Roe · order 2 · κ = −1' : 'SLAU2/Roe · Krylov · line search'}</span></div><div className="semantic-diff"><p className="eyebrow">STAGE CONTRACT</p><div><code>{mode === 'recovery' ? 'bounded diagnostic trajectory' : mode === 'accuracy' ? 'second-order reporting candidate' : 'steady efficiency evaluation'}</code><span>same CFD problem</span><ArrowRight size={14}/><strong>{modeLabel(mode)}</strong></div><small>{mode === 'recovery' ? 'Do not report first-order loads.' : mode === 'accuracy' ? 'Require force and mesh sensitivity before acceptance.' : 'Require steady compatibility and controlled line-search behavior.'}</small></div></div><button className="lesson-secondary-button" onClick={() => downloadJSON(params, mode)}><Download size={15}/> Download selected setup</button></>
      case 'acceptance': return <><div className="lesson-kicker"><ShieldCheck size={15}/> Acceptance and rollback</div><h1>A stable calculation is accepted only after accuracy and evidence gates pass.</h1><p className="lesson-lead">Define the rollback trigger before running each Draft. If second-order reconstruction or Krylov introduces a new failure, return to the last interpretable stage and inspect the first failing location instead of stacking more changes.</p><div className="evidence-checklist">{t16Evidence.map((item) => { const selected = reviewed.includes(item.title); return <button className={selected ? 'reviewed' : ''} key={item.title} onClick={() => setReviewed((current) => selected ? current.filter((value) => value !== item.title) : [...current, item.title])}><span className="evidence-check">{selected && <Check size={15}/>}</span><span><strong>{item.title}</strong><small>{item.detail}</small></span></button> })}</div><div className={`lesson-callout ${reviewed.length === t16Evidence.length ? 'success' : ''}`}>{reviewed.length === t16Evidence.length ? <CheckCircle2 size={17}/> : <AlertTriangle size={17}/>}<p><strong>{reviewed.length}/6 reviewed</strong>{reviewed.length === t16Evidence.length ? 'The numerical-diagnostics evidence contract is complete.' : 'Review every gate before creating the staged environment.'}</p></div><TutorialFailureModes items={t16Pedagogy.failureModes}/><TutorialEvidenceRubric items={t16Pedagogy.evidenceRubric}/></>
      default: return <><div className="lesson-kicker"><Cloud size={15}/> Create the numerical-diagnostics environment</div><h1>Create three configured Case Drafts from the supplied loaded vane.</h1><p className="lesson-lead">The app uploads the finite-span vane, registers a midspan Slice and adverse-gradient Box, and synchronizes the recovery, second-order, and steady Krylov/SLAU2 parameter sets.</p><div className="run-readiness-card"><div className="run-ready-icon"><CheckCircle2 size={30}/></div><div><span>CONFIGURATION STATUS</span><strong>All three numerical stages validated</strong><p>No surface mesh, volume mesh, or solver Case is submitted. Review each Draft and its rollback criterion in the Project workspace.</p></div></div><TutorialTransferCheck items={t16Pedagogy.transferQuestions}/><TutorialEnvironmentBuilder status={status} tutorialId="T16" defaultProjectName="Tutorial T16 · numerical diagnostics" heading="Build the T16 numerical-diagnostics environment" description="The app uploads the bundled loaded vane and creates recovery, second-order, and steady Krylov/SLAU2 Case Drafts." configurationSummary="Mach 0.30 at 12°, shared mesh and outputs, staged Roe recovery, second-order reporting candidate, Krylov/SLAU2 evaluation" draftKind="Case" draftCount={3} baselineValue="Stage 1 · conservative recovery" variantValue="Stage 2 · restored second order" thirdValue="Stage 3 · steady Krylov + SLAU2" successDescription="All three Case Draft parameter sets are synced. No surface mesh, volume mesh, or solver Case has been submitted." createEnvironment={createT16Environment}/></>
    }
  }
  return <div className="tutorial-player-page"><TopBar status={status} title="Guided tutorial · T16"/><aside className="tutorial-outline"><Link className="tutorial-back" to="/tutorials"><ArrowLeft size={14}/> All tutorials</Link><div className="tutorial-outline-title"><span>T16</span><h2>Numerical diagnostics</h2><small>Solver numerics · 25–30 min</small></div><div className="tutorial-progress"><div><span>Progress</span><strong>{t16Progress(completed)}%</strong></div><progress value={t16Progress(completed)} max="100"/></div><nav aria-label="Tutorial steps">{t16Steps.map((item, index) => <button key={item.id} className={`${index === stepIndex ? 'active' : ''} ${completed.includes(item.id) ? 'complete' : ''}`} onClick={() => setStepIndex(index)}><span>{completed.includes(item.id) ? <Check size={13}/> : item.label}</span><div><strong>{item.title}</strong><small>{item.summary}</small></div></button>)}</nav><button className="tutorial-reset" onClick={() => { setCompleted([]); setStepIndex(0); setReviewed([]); setChecksVisible(false); setMode('recovery') }}><RotateCcw size={13}/> Reset progress</button></aside><main className="tutorial-lesson"><div className="lesson-content">{lesson()}</div><footer className="lesson-footer"><button className="lesson-previous" disabled={stepIndex === 0} onClick={() => setStepIndex((current) => Math.max(0, current - 1))}><ArrowLeft size={15}/> Previous</button><span>Step {stepIndex + 1} of {t16Steps.length}</span>{stepIndex < t16Steps.length - 1 ? <button className="lesson-next" onClick={finishStep}>Complete & continue <ArrowRight size={15}/></button> : <button className="lesson-next" onClick={() => setCompleted((current) => current.includes(step.id) ? current : [...current, step.id])}><Check size={15}/> Mark tutorial complete</button>}</footer></main></div>
}
