import { AlertTriangle, ArrowLeft, ArrowRight, Check, CheckCircle2, Cloud, Download, GitBranch, Network, RotateCcw, ShieldCheck, Sparkles, Waves } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import type { Flow360Status } from '../api/client'
import { api } from '../api/client'
import TopBar from '../components/TopBar'
import TutorialEnvironmentBuilder from '../components/TutorialEnvironmentBuilder'
import { TutorialConceptBridge, TutorialDerivations, TutorialEvidenceRubric, TutorialFailureModes, TutorialPrediction, TutorialTransferCheck } from '../components/TutorialTeachingBlocks'
import { createT17Environment, t17Evidence, t17ParameterCards, t17Params, t17Pedagogy, t17Progress, t17Steps, validateT17Setup, type T17Mode } from '../tutorials/t17'

const storageKey = 'vibesim.tutorial.T17.completed'
function readProgress() { try { const parsed = JSON.parse(window.localStorage.getItem(storageKey) || '[]'); return Array.isArray(parsed) ? parsed.filter((item): item is string => typeof item === 'string') : [] } catch { return [] } }
function modeLabel(mode: T17Mode) { return mode === 'source' ? '8° source' : mode === 'uniform' ? '12° uniform' : mode === 'expression' ? '12° expression seed' : '12° modified restart' }
function downloadJSON(params: Record<string, unknown>, mode: T17Mode) { const blob = new Blob([`${JSON.stringify(params, null, 2)}\n`], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `T17-${mode}.simulation.json`; anchor.click(); URL.revokeObjectURL(url) }
function PathVisual({ mode }: { mode: T17Mode }) { return <svg className="tutorial-aircraft" viewBox="0 0 760 320" role="img" aria-label="Initialization paths from source and analytic fields to the target Case"><rect x="35" y="30" width="690" height="250" rx="24" fill="#e6eee4"/><circle cx="150" cy="160" r="55" fill="#f8faf3" stroke="#718343" strokeWidth="3"/><circle cx="610" cy="160" r="55" fill="#f8faf3" stroke="#397991" strokeWidth="3"/><path d="M205 135 C320 70 450 70 555 135 M205 160 H555 M205 185 C320 250 450 250 555 185" fill="none" stroke="#899389" strokeWidth="3"/><path d="M533 125 L558 136 L536 151 M533 150 L558 161 L533 176 M536 174 L558 185 L533 196" fill="none" stroke="#899389" strokeWidth="3"/><text x="105" y="154">8° source</text><text x="565" y="154">12° target</text><text x="270" y="72">fork / restart</text><text x="294" y="150">uniform field</text><text x="282" y="252">expression seed</text><text x="280" y="296">selected: {modeLabel(mode)}</text></svg> }

export default function T17TutorialPage() {
  const [status, setStatus] = useState<Flow360Status | null>(null); const [stepIndex, setStepIndex] = useState(0); const [completed, setCompleted] = useState<string[]>(readProgress); const [mode, setMode] = useState<T17Mode>('source'); const [checksVisible, setChecksVisible] = useState(false); const [reviewed, setReviewed] = useState<string[]>([])
  const params = useMemo(() => t17Params(mode), [mode]); const checks = useMemo(() => validateT17Setup(params), [params]); const step = t17Steps[stepIndex]
  useEffect(() => { api.flow360Status().then(setStatus).catch(() => setStatus({ available: false })) }, []); useEffect(() => window.localStorage.setItem(storageKey, JSON.stringify(completed)), [completed])
  const finishStep = () => { setCompleted((current) => current.includes(step.id) ? current : [...current, step.id]); setStepIndex((current) => Math.min(current + 1, t17Steps.length - 1)) }
  const lesson = () => {
    switch (step.id) {
      case 'decision': return <><div className="lesson-kicker"><Sparkles size={15}/> Engineering decision</div><h1>How should a 12° target Case begin after an 8° vane solution?</h1><p className="lesson-lead">Initialization controls the transient route into the target equations. Compare an independent target-freestream field, a bounded analytic wake seed, and a same-mesh fork from an accepted parent.</p><div className="lesson-decision-card"><span>DECISION</span><strong>Which path reduces work without changing the accepted 12° solution?</strong><p>Measure startup behavior and cost, then require final load and field agreement against the independent cold start.</p></div><div className="aircraft-stage"><PathVisual mode={mode}/></div><TutorialConceptBridge cfd={t17Pedagogy.cfdConcepts} flow360={t17Pedagogy.flow360Concepts}/></>
      case 'expressions': return <><div className="lesson-kicker"><Waves size={15}/> Initial fields</div><h1>Write the field in nondimensional solver variables and derive its bounds.</h1><p className="lesson-lead">The uniform branch uses the operating-condition variables rho, u, v, w, and p. The analytic branch applies a smooth Gaussian velocity deficit with a known 0.85 lower multiplier while leaving density and pressure at freestream.</p><div className="parameter-learning-grid">{t17ParameterCards.map((item) => <article key={item.label}><div><span className={`provenance ${item.provenance}`}>{item.provenance}</span><strong>{item.label}</strong></div><b>{item.value}</b><p>{item.why}</p></article>)}</div><TutorialDerivations items={t17Pedagogy.derivations}/><button className="lesson-validate-button" onClick={() => setChecksVisible(true)}><ShieldCheck size={16}/> Validate the selected initialization</button>{checksVisible && <div className="setup-checks">{checks.map((check) => <div className={check.passed ? 'passed' : 'failed'} key={check.id}>{check.passed ? <CheckCircle2 size={17}/> : <AlertTriangle size={17}/>}<span><strong>{check.label}</strong><small>{check.detail}</small></span></div>)}</div>}</>
      case 'parent': return <><div className="lesson-kicker"><ShieldCheck size={15}/> Parent qualification</div><h1>A completed Case becomes a restart parent only after its solution is accepted.</h1><p className="lesson-lead">Record the source Case ID, Volume Mesh ID, solver version, convergence histories, force stability, state bounds, and mesh evidence. Reusing an untrustworthy parent can make the child fail faster or converge quickly to the wrong state.</p><TutorialPrediction experiment={t17Pedagogy.experiments[0]}/><div className="lesson-callout warning"><AlertTriangle size={17}/><p><strong>Provenance boundary</strong>The modified-restart JSON contains no parent ID. Select the real source Case from the Project tree when creating the fork.</p></div><TutorialFailureModes items={t17Pedagogy.failureModes.slice(0, 2)}/></>
      case 'restart': return <><div className="lesson-kicker"><GitBranch size={15}/> Fork composition</div><h1>Keep state transformation and resource ancestry in their correct layers.</h1><p className="lesson-lead">For the same mesh, fork the accepted 8° Case and apply the 4° velocity rotation. For a different mesh, add interpolation and audit the transfer before judging target convergence.</p><div className="alpha-experiment"><div className="alpha-control" role="group" aria-label="Initialization strategy"><button className={mode === 'source' ? 'active' : ''} onClick={() => setMode('source')}><span>Source</span><strong>8° uniform</strong></button><button className={mode === 'uniform' ? 'active' : ''} onClick={() => setMode('uniform')}><span>Independent</span><strong>12° uniform</strong></button><button className={mode === 'expression' ? 'active' : ''} onClick={() => setMode('expression')}><span>Independent</span><strong>12° expression</strong></button><button className={mode === 'restart' ? 'active' : ''} onClick={() => setMode('restart')}><span>Requires parent</span><strong>12° restart</strong></button></div><div className="alpha-visual"><Network size={82} strokeWidth={1.1}/><span>{modeLabel(mode)}</span></div><div className="semantic-diff"><p className="eyebrow">RESOURCE CONTRACT</p><div><code>{mode === 'restart' ? 'ModifiedRestartSolution expressions' : 'InitialCondition expressions'}</code><span>plus</span><ArrowRight size={14}/><strong>{mode === 'restart' ? 'real parent Case selected in fork' : 'new Case from Geometry path'}</strong></div><small>{mode === 'restart' ? 'Do not save this as a standalone pre-run Draft.' : 'This configuration can be created before a source Case exists.'}</small></div></div><TutorialPrediction experiment={t17Pedagogy.experiments[1]}/><button className="lesson-secondary-button" onClick={() => downloadJSON(params, mode)}><Download size={15}/> Download selected setup</button></>
      case 'evidence': return <><div className="lesson-kicker"><ShieldCheck size={15}/> Acceptance evidence</div><h1>Separate saved work from final-state agreement.</h1><p className="lesson-lead">A useful initialization must improve accepted pseudo-steps or wall time and still converge to the same target loads and fields. Cross-mesh interpolation adds transfer-quality evidence before this comparison.</p><div className="evidence-checklist">{t17Evidence.map((item) => { const selected = reviewed.includes(item.title); return <button className={selected ? 'reviewed' : ''} key={item.title} onClick={() => setReviewed((current) => selected ? current.filter((value) => value !== item.title) : [...current, item.title])}><span className="evidence-check">{selected && <Check size={15}/>}</span><span><strong>{item.title}</strong><small>{item.detail}</small></span></button> })}</div><div className={`lesson-callout ${reviewed.length === t17Evidence.length ? 'success' : ''}`}>{reviewed.length === t17Evidence.length ? <CheckCircle2 size={17}/> : <AlertTriangle size={17}/>}<p><strong>{reviewed.length}/6 reviewed</strong>{reviewed.length === t17Evidence.length ? 'The initialization and restart evidence contract is complete.' : 'Review every gate before accepting an accelerated branch.'}</p></div><TutorialEvidenceRubric items={t17Pedagogy.evidenceRubric}/></>
      default: return <><div className="lesson-kicker"><Cloud size={15}/> Create the pre-run environment</div><h1>Create three valid Drafts now; create the restart fork after the source Case finishes.</h1><p className="lesson-lead">The app uploads the supplied vane and synchronizes the 8° source, 12° uniform cold start, and 12° expression-seed parameter sets. It deliberately does not create a parentless restart Draft.</p><div className="run-readiness-card"><div className="run-ready-icon"><CheckCircle2 size={30}/></div><div><span>CONFIGURATION STATUS</span><strong>Three pre-run Drafts validated</strong><p>Run and accept the source first. Then open its Case node in the Project tree, create a fork, and apply the downloadable modified-restart setup.</p></div></div><TutorialTransferCheck items={t17Pedagogy.transferQuestions}/><TutorialEnvironmentBuilder status={status} tutorialId="T17" defaultProjectName="Tutorial T17 · initialization and restart" heading="Build the T17 initialization environment" description="The app uploads the bundled vane and creates source, target cold-start, and target expression-seed Case Drafts." configurationSummary="Mach 0.30, 8° source, 12° uniform target, bounded 12° expression seed, shared mesh and comparison outputs" draftKind="Case" draftCount={3} baselineValue="Source · 8° uniform start" variantValue="Target · 12° uniform start" thirdValue="Target · 12° expression seed" successDescription="All three pre-run Case Drafts are synced. Create the modified-restart branch only from the real source Case after it has run and passed review." createEnvironment={createT17Environment}/></>
    }
  }
  return <div className="tutorial-player-page"><TopBar status={status} title="Guided tutorial · T17"/><aside className="tutorial-outline"><Link className="tutorial-back" to="/tutorials"><ArrowLeft size={14}/> All tutorials</Link><div className="tutorial-outline-title"><span>T17</span><h2>Initialization and restart</h2><small>Case continuation · 25–30 min</small></div><div className="tutorial-progress"><div><span>Progress</span><strong>{t17Progress(completed)}%</strong></div><progress value={t17Progress(completed)} max="100"/></div><nav aria-label="Tutorial steps">{t17Steps.map((item, index) => <button key={item.id} className={`${index === stepIndex ? 'active' : ''} ${completed.includes(item.id) ? 'complete' : ''}`} onClick={() => setStepIndex(index)}><span>{completed.includes(item.id) ? <Check size={13}/> : item.label}</span><div><strong>{item.title}</strong><small>{item.summary}</small></div></button>)}</nav><button className="tutorial-reset" onClick={() => { setCompleted([]); setStepIndex(0); setReviewed([]); setChecksVisible(false); setMode('source') }}><RotateCcw size={13}/> Reset progress</button></aside><main className="tutorial-lesson"><div className="lesson-content">{lesson()}</div><footer className="lesson-footer"><button className="lesson-previous" disabled={stepIndex === 0} onClick={() => setStepIndex((current) => Math.max(0, current - 1))}><ArrowLeft size={15}/> Previous</button><span>Step {stepIndex + 1} of {t17Steps.length}</span>{stepIndex < t17Steps.length - 1 ? <button className="lesson-next" onClick={finishStep}>Complete & continue <ArrowRight size={15}/></button> : <button className="lesson-next" onClick={() => setCompleted((current) => current.includes(step.id) ? current : [...current, step.id])}><Check size={15}/> Mark tutorial complete</button>}</footer></main></div>
}
